import { Article } from '../types';

export const CONSTITUTION_ARTICLES: Article[] = [
  // PART I: THE UNION AND ITS TERRITORY
  {
    id: "Article 1",
    title: "Name and territory of the Union",
    summary: "India, also known as Bharat, is a Union of States. Its territory comprises states, union territories, and any acquired territories, signifying an indivisible and permanent union.",
    detailedExplanation: "This foundational article establishes the identity of the nation with two official names, 'India' and 'Bharat'. It defines the country's political structure as a 'Union of States' to signify that India is an indivisible whole and that states have no right to secede. The territory of India is explicitly defined to include the territories of the States, the Union territories as specified in the First Schedule, and any other territories that may be acquired in the future. This underscores the unity and integrity of the nation.",
    fullText: "(1) India, that is Bharat, shall be a Union of States.\n(2) The States and the territories thereof shall be as specified in the First Schedule.\n(3) The territory of India shall comprise—\n(a) the territories of the States;\n(b) the Union territories specified in the First Schedule; and\n(c) such other territories as may be acquired.",
    part: "Part I: The Union and its Territory",
    landmarkCases: [
      { caseName: "In re Berubari Union (1960)", caseSummary: "The Supreme Court held that the power of Parliament to diminish the area of a state (under Article 3) does not cover the cession of Indian territory to a foreign country. This must be done through a constitutional amendment under Article 368." }
    ],
    tags: ["Union", "Territory", "Bharat", "State Formation"],
    limitationsAndExceptions: "The term 'Union of States' signifies that states cannot secede from India. India is an indivisible and permanent Union.",
    relatedArticles: ["Article 2", "Article 3"],
  },
  {
    id: "Article 2",
    title: "Admission or establishment of new States",
    summary: "Gives Parliament the power to admit new territories into India or establish new states that are not part of India's existing territory, as seen with the integration of Sikkim.",
    detailedExplanation: "Article 2 grants Parliament the power to admit into the Union, or establish, new States that are not currently part of India. The term 'admit' refers to including an existing political entity, while 'establish' refers to creating a new state from a territory that was not previously a state. This power allows India to expand its territory. A prime example is the case of Sikkim, which was an independent monarchy that became an 'Associate State' and was later formally admitted into the Indian Union as the 22nd state in 1975.",
    fullText: "Parliament may by law admit into the Union, or establish, new States on such terms and conditions as it thinks fit.",
    part: "Part I: The Union and its Territory",
    landmarkCases: [],
    tags: ["Parliament", "New States", "Admission", "Sikkim"],
    limitationsAndExceptions: "This power applies to territories outside India's existing boundaries. The terms and conditions for admission or establishment are at the complete discretion of the Parliament.",
    relatedArticles: ["Article 1", "Article 3", "Article 4"],
  },
  {
    id: "Article 3",
    title: "Formation of new States and alteration of areas, boundaries or names of existing States",
    summary: "Empowers Parliament to form new states, alter areas, boundaries, or names of existing states within India. The state's opinion is not binding on Parliament.",
    detailedExplanation: "This article gives Parliament the power to reorganize the states internally by law. It can form a new state, increase or diminish the area of any state, alter its boundaries, or change its name. This power highlights the flexibility of India's federal structure. The procedure requires that a bill for this purpose can only be introduced on the recommendation of the President, who must refer the bill to the legislature of the affected state for its views. However, Parliament is not bound by these views. This led to the linguistic reorganization of states after independence, based on the recommendations of bodies like the Fazal Ali Commission in 1953.",
    fullText: "Parliament may by law—\n(a) form a new State by separation of territory from any State or by uniting two or more States or parts of States or by uniting any territory to a part of any State;\n(b) increase the area of any State;\n(c) diminish the area of any State;\n(d) alter the boundaries of any State;\n(e) alter the name of any State:\nProvided that no Bill for the purpose shall be introduced in either House of Parliament except on the recommendation of the President and unless, where the proposal contained in the Bill affects the area, boundaries or name of any of the States, the Bill has been referred by the President to the Legislature of that State for expressing its views thereon...",
    part: "Part I: The Union and its Territory",
    landmarkCases: [],
    tags: ["State Reorganization", "Parliament", "Boundaries"],
    limitationsAndExceptions: "A bill for such changes requires prior recommendation from the President and must be referred to the state legislature for its opinion, but this opinion is not binding on Parliament. Such laws can be passed by a simple majority.",
    relatedArticles: ["Article 1", "Article 2", "Article 4"],
  },
  {
    id: "Article 4",
    title: "Laws made under Articles 2 and 3 to provide for the amendment of the First and the Fourth Schedules",
    summary: "Clarifies that laws made under Articles 2 and 3, which alter state boundaries, are not considered constitutional amendments under Article 368 and can be passed by a simple majority.",
    detailedExplanation: "Article 4 is a consequential provision that clarifies the legislative process for laws made under Articles 2 and 3. It states that any such law will contain provisions to amend the First Schedule (listing states and UTs) and the Fourth Schedule (allocating Rajya Sabha seats) as necessary. Crucially, it declares that no such law shall be considered a constitutional amendment under Article 368. This mechanism allows for the territorial reorganization of India through a simple majority in Parliament, providing flexibility to the Union to meet changing administrative needs.",
    fullText: "(1) Any law referred to in article 2 or article 3 shall contain such provisions for the amendment of the First Schedule and the Fourth Schedule as may be necessary to give effect to the provisions of the law...\n(2) No such law as aforesaid shall be deemed to be an amendment of this Constitution for the purposes of article 368.",
    part: "Part I: The Union and its Territory",
    landmarkCases: [],
    tags: ["Simple Majority", "Constitutional Amendment", "Schedules"],
    limitationsAndExceptions: "Such laws shall not be deemed a constitutional amendment under Article 368, simplifying the process of state reorganization.",
    relatedArticles: ["Article 2", "Article 3"],
  },
  // PART II: CITIZENSHIP
  {
    id: "Article 5",
    title: "Citizenship at the commencement of the Constitution",
    summary: "Defines who was a citizen of India on January 26, 1950, based on domicile and either birth in India, parent's birth in India, or residence for at least five years.",
    detailedExplanation: "This article laid down the rules for who would be considered a citizen of India when the Constitution came into force. The mandatory condition was 'domicile' in India (permanent residence). Along with domicile, one of the following three conditions had to be met: (a) the person was born in India, (b) either of their parents was born in India, or (c) they had been ordinarily residing in India for at least five years before commencement. This article came into effect on November 26, 1949, itself.",
    fullText: "At the commencement of this Constitution, every person who has his domicile in the territory of India and—\n(a) who was born in the territory of India; or\n(b) either of whose parents was born in the territory of India; or\n(c) who has been ordinarily resident in the territory of India for not less than five years immediately preceding such commencement, shall be a citizen of India.",
    part: "Part II: Citizenship",
    landmarkCases: [],
    tags: ["Citizenship", "Domicile"],
    limitationsAndExceptions: "These provisions were applicable only at the commencement of the Constitution. Future matters of citizenship are governed by laws made by Parliament under Article 11, such as the Citizenship Act, 1955.",
    relatedArticles: ["Article 6", "Article 7", "Article 8", "Article 9", "Article 10", "Article 11"],
  },
  {
    id: "Article 6",
    title: "Rights of citizenship of certain persons who have migrated to India from Pakistan",
    summary: "Grants citizenship to people who migrated from Pakistan to India before July 19, 1948, or those who migrated after but registered as citizens.",
    detailedExplanation: "This article was created to address the mass migration during the Partition. It granted citizenship to those who moved from Pakistan to India. It set a cut-off date of July 19, 1948. Those who migrated before this date became citizens if they ordinarily resided in India. Those who migrated on or after this date had to reside in India for at least six months and then register with a government officer to become a citizen. A mandatory condition for all under this article was that the person, or their parents or grandparents, must have been born in undivided India as defined by the Government of India Act, 1935.",
    fullText: "Notwithstanding anything in article 5, a person who has migrated to the territory of India from the territory now included in Pakistan shall be deemed to be a citizen of India at the commencement of this Constitution if—\n(a) he or either of his parents or any of his grand-parents was born in India as defined in the Government of India Act, 1935 (as originally enacted); and\n(b) (i) in the case where such person has so migrated before the nineteenth day of July, 1948, he has been ordinarily resident in the territory of India since the date of his migration, or\n(ii) in the case where such person has so migrated on or after the nineteenth day of July, 1948, he has been registered as a citizen of India...",
    part: "Part II: Citizenship",
    landmarkCases: [],
    tags: ["Citizenship", "Partition", "Migration"],
    limitationsAndExceptions: "This provision is specific to the historical context of Partition and is not applicable to modern migration. It overrides Article 5 for the specific group of people it addresses.",
    relatedArticles: ["Article 5", "Article 7"],
  },
  {
    id: "Article 7",
    title: "Rights of citizenship of certain migrants to Pakistan",
    summary: "Strips Indian citizenship from those who migrated to Pakistan after March 1, 1947, but allows them to regain it if they return to India under a permit for resettlement.",
    detailedExplanation: "This article deals with individuals who migrated from India to Pakistan after March 1, 1947. It states that such persons shall not be considered citizens of India. This was to address the two-way migration during Partition. However, it provides an exception for those who returned to India with a permit for resettlement or permanent return. Such persons were treated as if they had migrated to India after July 19, 1948, and could acquire citizenship through registration as per Article 6(b)(ii). This provision ensured that those who returned to India permanently were not left stateless.",
    fullText: "Notwithstanding anything in articles 5 and 6, a person who has after the first day of March, 1947, migrated from the territory of India to the territory now included in Pakistan shall not be deemed to be a citizen of India:\nProvided that nothing in this article shall apply to a person who, after having so migrated..., has returned to the territory of India under a permit for resettlement or permanent return...",
    part: "Part II: Citizenship",
    landmarkCases: [],
    tags: ["Citizenship", "Partition", "Migration"],
    limitationsAndExceptions: "This article overrides Articles 5 and 6. It has a specific historical context tied to Partition. The exception for return is not automatic and requires a valid government-issued permit for resettlement.",
    relatedArticles: ["Article 5", "Article 6"],
  },
  {
    id: "Article 8",
    title: "Rights of citizenship of certain persons of Indian origin residing outside India",
    summary: "Grants Indian citizenship to persons of Indian origin (PIO) residing outside undivided India, if they or their parents/grandparents were born in undivided India and they register as a citizen with an Indian diplomatic mission.",
    detailedExplanation: "This article extends a path to citizenship for the Indian diaspora. It allows a person of Indian origin residing outside undivided India to become a citizen if they, or their parents or grandparents, were born in India (as defined in the 1935 Act). To acquire citizenship under this article, the person must formally apply and be registered by an Indian diplomatic or consular representative in their country of residence. This provision honors the connection of the Indian diaspora to their motherland. In line with this, the government later introduced schemes like PIO and OCI cards.",
    fullText: "Notwithstanding anything in article 5, any person who or either of whose parents or any of whose grand-parents was born in India... and who is ordinarily residing in any country outside India... shall be deemed to be a citizen of India if he has been registered as a citizen of India by the diplomatic or consular representative of India in the country where he is for the time being residing...",
    part: "Part II: Citizenship",
    landmarkCases: [],
    tags: ["Citizenship", "PIO", "Diaspora"],
    limitationsAndExceptions: "This is not an automatic grant of citizenship. The person of Indian origin must make a formal application and be registered by a diplomatic or consular representative.",
    relatedArticles: ["Article 5"],
  },
  {
    id: "Article 9",
    title: "Persons voluntarily acquiring citizenship of a foreign State not to be citizens",
    summary: "A person who voluntarily acquires the citizenship of a foreign country shall no longer be a citizen of India.",
    detailedExplanation: "This article firmly establishes the principle of single citizenship in India. It explicitly states that any person who voluntarily acquires the citizenship of another country automatically loses their Indian citizenship. This provision applies to those who would otherwise be citizens under Articles 5, 6, or 8. It ensures that there is no dual citizenship. Other grounds for termination of citizenship are detailed in the Citizenship Act, 1955.",
    fullText: "No person shall be a citizen of India by virtue of article 5, or be deemed to be a citizen of India by virtue of article 6 or article 8, if he has voluntarily acquired the citizenship of any foreign State.",
    part: "Part II: Citizenship",
    landmarkCases: [],
    tags: ["Citizenship", "Dual Citizenship", "Termination"],
    limitationsAndExceptions: "The loss of Indian citizenship is automatic upon voluntarily acquiring foreign citizenship. The article enforces the principle of single citizenship without exception.",
    relatedArticles: ["Article 5", "Article 10", "Article 11"],
  },
  {
    id: "Article 10",
    title: "Continuance of the rights of citizenship",
    summary: "Every person who is a citizen of India under any of the foregoing provisions shall continue to be a citizen, subject to any law made by Parliament.",
    detailedExplanation: "This article ensures the continuity of citizenship for those who became citizens at the commencement of the Constitution under Articles 5 to 8. It guarantees that their citizenship status will continue. However, this right is not absolute and is explicitly made subject to any laws that Parliament might enact. This provision links the constitutional grant of citizenship to Parliament's future legislative power over the matter, as detailed in Article 11.",
    fullText: "Every person who is or is deemed to be a citizen of India under any of the foregoing provisions of this Part shall, subject to the provisions of any law that may be made by Parliament, continue to be such citizen.",
    part: "Part II: Citizenship",
    landmarkCases: [],
    tags: ["Citizenship", "Parliament"],
    limitationsAndExceptions: "The right to continue as a citizen is not absolute. It is subject to laws made by Parliament, which can regulate the conditions for termination or deprivation of citizenship.",
    relatedArticles: ["Article 5", "Article 11"],
  },
  {
    id: "Article 11",
    title: "Parliament to regulate the right of citizenship by law",
    summary: "Gives Parliament the exclusive power to make any provision with respect to the acquisition and termination of citizenship and all other matters relating to it.",
    detailedExplanation: "While Articles 5-10 dealt with citizenship at the time of the Constitution's commencement, Article 11 is a forward-looking provision that grants Parliament exclusive and complete authority over all aspects of citizenship. This includes making laws for the acquisition and termination of citizenship after 1950. Using this power, Parliament enacted the Citizenship Act, 1955, which specifies various modes of acquiring citizenship such as by birth, descent, registration, and naturalization, and also outlines the grounds for its termination. This Act has been amended several times to meet changing needs.",
    fullText: "Nothing in the foregoing provisions of this Part shall derogate from the power of Parliament to make any provision with respect to the acquisition and termination of citizenship and all other matters relating to citizenship.",
    part: "Part II: Citizenship",
    landmarkCases: [],
    tags: ["Citizenship", "Parliament", "Citizenship Act"],
    limitationsAndExceptions: "This article grants plenary power to Parliament over citizenship laws. The laws made under this article must, however, be consistent with other provisions of the Constitution, including Fundamental Rights.",
    relatedArticles: ["Article 5", "Article 9", "Article 10"],
  },
  {
    id: "Article 12",
    title: "Definition of 'the State'",
    summary: "Defines 'the State' to include the Government and Parliament of India, state governments and legislatures, and all local or other authorities within India or under the control of the Government of India.",
    detailedExplanation: "This article is crucial as Fundamental Rights are primarily enforceable against 'the State'. Article 12 provides a broad definition to include all levels of government: the Union executive and legislature, state executives and legislatures, and local self-government institutions like Panchayats and Municipalities. The term 'other authorities' has been interpreted by the Supreme Court to include any body that is an 'agency or instrumentality' of the government, such as public sector undertakings, thereby expanding the scope of accountability for upholding fundamental rights.",
    fullText: "In this Part, unless the context otherwise requires, 'the State' includes the Government and Parliament of India and the Government and the Legislature of each of the States and all local or other authorities within the territory of India or under the control of the Government of India.",
    part: "Part III: Fundamental Rights",
    landmarkCases: [
      { caseName: "Ajay Hasia v. Khalid Mujib (1981)", caseSummary: "The Supreme Court laid down a comprehensive test to determine if a body is an 'instrumentality' of the State, considering factors like financial control, functional character, and deep and pervasive state control." }
    ],
    tags: ["Fundamental Rights", "State", "Definition"],
    limitationsAndExceptions: "The definition is broad but primarily covers governmental and quasi-governmental bodies. The actions of purely private individuals are generally outside its scope, except for certain rights like Article 17 (Untouchability).",
    relatedArticles: ["Article 13", "Article 32", "Article 36"],
  },
  {
    id: "Article 13",
    title: "Laws inconsistent with or in derogation of the fundamental rights",
    summary: "Declares that any law which is inconsistent with or takes away any of the fundamental rights shall be void. This establishes the power of judicial review.",
    detailedExplanation: "Article 13 is the 'protective shield' of Fundamental Rights and the foundation of judicial review. Clause (1) voids all pre-constitutional laws that are inconsistent with Fundamental Rights. Clause (2) prohibits the State from making any new law that abridges or takes away these rights. The term 'law' is defined broadly in Clause (3) to include ordinances, orders, customs, etc. A significant debate arose whether a 'constitutional amendment' is a 'law' under Article 13. The Supreme Court in the Kesavananda Bharati case resolved this by introducing the 'Basic Structure Doctrine,' holding that while Parliament can amend the Constitution, it cannot alter its basic structure, which includes many Fundamental Rights.",
    fullText: "(1) All laws in force in the territory of India immediately before the commencement of this Constitution, in so far as they are inconsistent with the provisions of this Part, shall, to the extent of such inconsistency, be void.\n(2) The State shall not make any law which takes away or abridges the rights conferred by this Part and any law made in contravention of this clause shall, to the extent of the contravention, be void...",
    part: "Part III: Fundamental Rights",
    landmarkCases: [
      { caseName: "Kesavananda Bharati v. State of Kerala (1973)", caseSummary: "The Supreme Court introduced the 'Basic Structure Doctrine,' ruling that Parliament cannot amend the Constitution in a way that alters its fundamental framework, which includes the essence of Fundamental Rights." },
      { caseName: "Golaknath vs. State of Punjab (1967)", caseSummary: "The court ruled that a constitutional amendment is also a 'law' under Article 13 and cannot abridge Fundamental Rights, a position later modified by the Kesavananda Bharati case." }
    ],
    tags: ["Fundamental Rights", "Judicial Review", "Basic Structure"],
    limitationsAndExceptions: "Clause (4), added by the 24th Amendment, states that Article 13 does not apply to constitutional amendments under Article 368. However, the 'Basic Structure Doctrine' from the Kesavananda Bharati case acts as a check on this.",
    relatedArticles: ["Article 12", "Article 32"],
  },
  {
    id: "Article 14",
    title: "Equality before law",
    summary: "The State shall not deny to any person equality before the law or the equal protection of the laws within the territory of India.",
    detailedExplanation: "Article 14 guarantees the right to equality to every person, citizen or foreigner. It has two aspects: 'Equality before the law,' a British concept, means no person is above the law. 'Equal protection of the laws,' an American concept, means that law should be applied equally to all persons who are similarly situated. It permits 'reasonable classification' for the purpose of legislation but prohibits arbitrary action. The Supreme Court has held that arbitrariness is the antithesis of equality.",
    fullText: "The State shall not deny to any person equality before the law or the equal protection of the laws within the territory of India.",
    part: "Part III: Fundamental Rights",
    landmarkCases: [
      { caseName: "E. P. Royappa v. State of Tamil Nadu (1974)", caseSummary: "The Supreme Court expanded Article 14's scope, stating that equality is a dynamic concept and is antithetical to arbitrariness. Any state action that is arbitrary is a violation of Article 14." }
    ],
    tags: ["Fundamental Rights", "Equality"],
    limitationsAndExceptions: "The right is not absolute and allows for 'reasonable classification'. The classification must be based on an intelligible differentia and must have a rational nexus to the objective of the law.",
    relatedArticles: ["Article 15", "Article 16", "Article 17", "Article 18", "Article 21"],
    fillInTheBlanks: [{ question: "The State shall not deny to any person equality before the law or the ____ protection of the laws.", answer: "equal" }]
  },
   {
    id: "Article 15",
    title: "Prohibition of discrimination on grounds of religion, race, caste, sex or place of birth",
    summary: "Prohibits the State from discriminating against any citizen on grounds only of religion, race, caste, sex, or place of birth. It also allows for special provisions for women, children, and backward classes.",
    detailedExplanation: "Article 15 is a specific application of equality, prohibiting discrimination on five specific grounds. Clause (1) prohibits state discrimination, while Clause (2) extends this to public places like shops, hotels, wells, and roads. Crucially, the article contains exceptions for affirmative action: Clause (3) allows special provisions for women and children. Clause (4) (added by the 1st Amendment) allows special provisions for the advancement of socially and educationally backward classes (SCs and STs). Clause (5) allows for reservations in educational institutions, and Clause (6) (added by the 103rd Amendment) provides for reservation for Economically Weaker Sections (EWS).",
    fullText: "(1) The State shall not discriminate against any citizen on grounds only of religion, race, caste, sex, place of birth or any of them.\n(2) No citizen shall, on grounds only of religion, race, caste, sex, place of birth or any of them, be subject to any disability, liability, restriction or condition with regard to—\n(a) access to shops, public restaurants, hotels and places of public entertainment; or\n(b) the use of wells, tanks, bathing ghats, roads and places of public resort...",
    part: "Part III: Fundamental Rights",
    landmarkCases: [
      { caseName: "State of Madras v. Champakam Dorairajan (1951)", caseSummary: "This case led to the First Constitutional Amendment, which added Article 15(4) to enable reservations in educational institutions for backward classes." },
      { caseName: "Indra Sawhney v. Union of India (1992)", caseSummary: "The 'Mandal case' upheld OBC reservations but introduced the 'creamy layer' concept and a 50% cap on total reservations." }
    ],
    tags: ["Fundamental Rights", "Equality", "Discrimination", "Reservation"],
    limitationsAndExceptions: "The prohibition on discrimination is on the specified grounds 'only'. The article itself contains positive exceptions in clauses (3), (4), (5), and (6) to allow the state to make special provisions (affirmative action) for specific groups.",
    relatedArticles: ["Article 14", "Article 16", "Article 29", "Article 46"],
  },
  {
    id: "Article 16",
    title: "Equality of opportunity in matters of public employment",
    summary: "Guarantees equality of opportunity for all citizens in matters of public employment and prohibits discrimination on grounds of religion, race, caste, sex, descent, place of birth, or residence.",
    detailedExplanation: "This article ensures a level playing field for all citizens in government jobs. It prohibits discrimination on seven specific grounds. Like Article 15, it contains important exceptions for affirmative action. Clause (4) allows the state to reserve posts for backward classes not adequately represented. Later amendments added Clause (4A) for reservation in promotions for SCs/STs, Clause (4B) for carrying forward backlog vacancies, and Clause (6) for reservation for Economically Weaker Sections (EWS).",
    fullText: "(1) There shall be equality of opportunity for all citizens in matters relating to employment or appointment to any office under the State.\n(2) No citizen shall, on grounds only of religion, race, caste, sex, descent, place of birth, residence or any of them, be ineligible for, or discriminated against in respect of, any employment or office under the State...",
    part: "Part III: Fundamental Rights",
    landmarkCases: [
      { caseName: "Indra Sawhney v. Union of India (1992)", caseSummary: "Upheld 27% reservation for OBCs in public employment but ruled that reservation in promotions is unconstitutional (later overturned by amendment) and set a 50% ceiling on reservations." },
      { caseName: "M. Nagaraj v. Union of India (2006)", caseSummary: "Upheld reservations in promotions for SCs/STs but imposed conditions on the state to demonstrate backwardness, inadequate representation, and maintenance of administrative efficiency." }
    ],
    tags: ["Fundamental Rights", "Equality", "Public Employment", "Reservation"],
    limitationsAndExceptions: "This article allows for reservations in public employment for backward classes, SCs, STs, and EWS. Parliament can also prescribe residence as a condition for certain employments (Clause 3). It also allows for religious considerations in appointments to religious institutions (Clause 5).",
    relatedArticles: ["Article 14", "Article 15", "Article 46"],
  },
  {
    id: "Article 17",
    title: "Abolition of Untouchability",
    summary: "'Untouchability' is abolished and its practice in any form is forbidden. Enforcing any disability arising from 'Untouchability' is a punishable offence.",
    detailedExplanation: "This is a powerful and absolute provision aimed at eradicating the social evil of untouchability. It is one of the few fundamental rights enforceable against both the state and private individuals. The Constitution does not define 'untouchability,' but it is understood as the historical practice of imposing social disabilities on certain classes of people by reason of their birth. To enforce this article, Parliament enacted punitive laws, including the Protection of Civil Rights Act, 1955, and the more stringent Scheduled Castes and Scheduled Tribes (Prevention of Atrocities) Act, 1989.",
    fullText: "'Untouchability' is abolished and its practice in any form is forbidden. The enforcement of any disability arising out of 'Untouchability' shall be an offence punishable in accordance with law.",
    part: "Part III: Fundamental Rights",
    landmarkCases: [
      { caseName: "People's Union for Democratic Rights v. Union of India (1982)", caseSummary: "The Supreme Court held that the fundamental right under Article 17 is enforceable against private individuals as well, and it is the constitutional duty of the state to take necessary steps to prevent its violation." }
    ],
    tags: ["Fundamental Rights", "Equality", "Untouchability", "Discrimination"],
    limitationsAndExceptions: "This right is absolute and has no constitutional limitations. Its effectiveness depends on the strict enforcement of laws passed by Parliament to punish acts of untouchability.",
    relatedArticles: ["Article 14", "Article 15"],
    fillInTheBlanks: [{ question: "'____' is abolished and its practice in any form is forbidden.", answer: "Untouchability" }]
  },
  {
    id: "Article 18",
    title: "Abolition of titles",
    summary: "Prohibits the State from conferring titles, except for military and academic distinctions. Citizens of India are also prohibited from accepting any title from a foreign state.",
    detailedExplanation: "This article aims to establish social equality by abolishing hereditary titles of nobility like 'Sir', 'Rai Bahadur', etc., which created a hierarchical social order. The state is barred from conferring any titles except military (e.g., General) and academic (e.g., Dr.) distinctions, which are based on merit. Citizens cannot accept foreign titles. National awards like Bharat Ratna are considered honors, not titles, and cannot be used as prefixes or suffixes to a person's name.",
    fullText: "(1) No title, not being a military or academic distinction, shall be conferred by the State.\n(2) No citizen of India shall accept any title from any foreign State...",
    part: "Part III: Fundamental Rights",
    landmarkCases: [
      { caseName: "Balaji Raghavan v. Union of India (1996)", caseSummary: "The Supreme Court upheld national awards like Bharat Ratna, clarifying they are not 'titles' under Article 18. The Court, however, stated they cannot be used as prefixes or suffixes to names." }
    ],
    tags: ["Fundamental Rights", "Equality", "Titles"],
    limitationsAndExceptions: "The article explicitly exempts military and academic distinctions. National Awards are permitted as honors but not as titles to be used with a name.",
    relatedArticles: ["Article 14"],
  },
  {
    id: "Article 19",
    title: "Protection of certain rights regarding freedom of speech, etc.",
    summary: "Guarantees six fundamental freedoms: speech and expression, assembly, association, movement, residence, and profession, subject to reasonable restrictions.",
    detailedExplanation: "Article 19(1) guarantees six essential freedoms for citizens: (a) speech and expression, (b) peaceful assembly without arms, (c) forming associations or unions, (d) moving freely throughout India, (e) residing and settling in any part of India, and (g) practicing any profession, or carrying on any occupation, trade or business. These freedoms are not absolute and are subject to 'reasonable restrictions' by the state on grounds specified in clauses (2) to (6), such as sovereignty and integrity of India, public order, decency, or morality.",
    fullText: "(1) All citizens shall have the right—\n(a) to freedom of speech and expression;\n(b) to assemble peaceably and without arms;\n(c) to form associations or unions or co-operative societies;\n(d) to move freely throughout the territory of India;\n(e) to reside and settle in any part of the territory of India; and\n(g) to practise any profession, or to carry on any occupation, trade or business...",
    part: "Part III: Fundamental Rights",
    landmarkCases: [
       { caseName: "Shreya Singhal v. Union of India (2015)", caseSummary: "The Supreme Court struck down Section 66A of the IT Act as unconstitutional, holding it violated freedom of speech and expression for being vague and overbroad." }
    ],
    tags: ["Fundamental Rights", "Freedom of Speech", "Liberty"],
    limitationsAndExceptions: "All freedoms are subject to 'reasonable restrictions' by the State on specific grounds mentioned in clauses (2) to (6) of Article 19, such as public order, national security, decency, and morality.",
    relatedArticles: ["Article 21", "Article 20"],
  },
  {
    id: "Article 20",
    title: "Protection in respect of conviction for offences",
    summary: "Provides three safeguards for accused persons: protection against ex-post-facto law, double jeopardy, and self-incrimination.",
    detailedExplanation: "This article provides three crucial protections to any person accused of a crime: (1) No ex-post-facto law: A person cannot be convicted for an act that was not an offence when committed, nor be given a penalty greater than what was prescribed at that time. (2) No double jeopardy: A person cannot be prosecuted and punished for the same offence more than once. (3) No self-incrimination: An accused person cannot be compelled to be a witness against themselves. These are fundamental to a fair criminal justice system and remain in force even during an emergency.",
    fullText: "(1) No person shall be convicted of any offence except for violation of a law in force at the time of the commission of the Act charged as an offence...\n(2) No person shall be prosecuted and punished for the same offence more than once.\n(3) No person accused of any offence shall be compelled to be a witness against himself.",
    part: "Part III: Fundamental Rights",
    landmarkCases: [
        { caseName: "Selvi v. State of Karnataka (2010)", caseSummary: "The Supreme Court held that compelling an accused to undergo narco-analysis, polygraph, or brain-mapping tests violates the protection against self-incrimination under Article 20(3)." }
    ],
    tags: ["Fundamental Rights", "Criminal Justice", "Liberty"],
    limitationsAndExceptions: "Protection against ex-post-facto laws applies only to criminal laws. Protection against double jeopardy applies only to punishment by a court, not departmental proceedings. Protection against self-incrimination does not extend to compulsory production of material objects or giving physical evidence like fingerprints or DNA samples.",
    relatedArticles: ["Article 19", "Article 21", "Article 22"],
  },
  {
    id: "Article 21",
    title: "Protection of life and personal liberty",
    summary: "No person shall be deprived of their life or personal liberty except according to procedure established by law. This right is available to both citizens and non-citizens.",
    detailedExplanation: "Article 21 is one of the most significant fundamental rights, with a very wide scope. The Supreme Court has interpreted 'life' to mean more than mere survival; it includes the right to live with human dignity. 'Personal liberty' has also been given a broad meaning. The 'procedure established by law' must be fair, just, and reasonable. The Court has read numerous rights into Article 21, including the right to privacy, right to a clean environment, right to speedy trial, right to health, and right to shelter. This right cannot be suspended, even during an emergency.",
    fullText: "No person shall be deprived of his life or personal liberty except according to procedure established by law.",
    part: "Part III: Fundamental Rights",
    landmarkCases: [
      { caseName: "Maneka Gandhi v. Union of India (1978)", caseSummary: "The Supreme Court held that the 'procedure established by law' under Article 21 must be fair, just, and reasonable, effectively introducing the concept of 'substantive due process'." },
      { caseName: "Justice K.S. Puttaswamy (Retd.) v. Union of India (2017)", caseSummary: "A nine-judge bench unanimously affirmed that the Right to Privacy is a fundamental right, intrinsic to the right to life and personal liberty under Article 21." }
    ],
    tags: ["Fundamental Rights", "Life and Liberty", "Privacy"],
    limitationsAndExceptions: "This right can be curtailed only 'according to procedure established by law,' which must be fair, just, and reasonable. This right cannot be suspended even during a national emergency.",
    relatedArticles: ["Article 14", "Article 19", "Article 20", "Article 21A", "Article 22"],
  },
  {
    id: "Article 21A",
    title: "Right to education",
    summary: "The State shall provide free and compulsory education to all children of the age of six to fourteen years.",
    detailedExplanation: "Inserted by the 86th Amendment in 2002, this article elevated the right to education to a fundamental right. It places a positive obligation on the state to provide free and compulsory elementary education to all children between 6 and 14 years old. To implement this, Parliament enacted the Right of Children to Free and Compulsory Education (RTE) Act in 2009. The struggle for this right was long, with historical demands from figures like Mahatma Phule and Shahu Maharaj.",
    fullText: "The State shall provide free and compulsory education to all children of the age of six to fourteen years in such manner as the State may, by law, determine.",
    part: "Part III: Fundamental Rights",
    landmarkCases: [
      { caseName: "Unni Krishnan, J.P. v. State of Andhra Pradesh (1993)", caseSummary: "The court held that the right to education is a fundamental right under Article 21, but limited it to free education for children up to the age of 14. This judgment was instrumental in the insertion of Article 21A." }
    ],
    tags: ["Fundamental Rights", "Education"],
    limitationsAndExceptions: "The right is specific to the age group of 6 to 14 years. It does not cover early childhood care (below 6 years) or higher education, which are covered under Directive Principles.",
    relatedArticles: ["Article 21", "Article 45", "Article 51A"],
    fillInTheBlanks: [{ question: "The State shall provide free and compulsory education to all children of the age of ____ to fourteen years.", answer: "six" }]
  },
  {
    id: "Article 22",
    title: "Protection against arrest and detention in certain cases",
    summary: "Provides procedural safeguards against arbitrary arrest and detention, including the right to be informed of grounds of arrest, consult a lawyer, and be produced before a magistrate within 24 hours.",
    detailedExplanation: "This article provides safeguards against two types of detention: punitive (arrest after a crime) and preventive (detention on suspicion). For punitive detention, it guarantees the right to be informed of the grounds of arrest, the right to a lawyer, and the right to be produced before a magistrate within 24 hours. These rights are not available to enemy aliens or those under preventive detention. For preventive detention, the article sets a maximum detention period of 3 months, which can be extended only on the recommendation of an Advisory Board. Laws like TADA, POTA, and UAPA have been controversial preventive detention laws.",
    fullText: "(1) No person who is arrested shall be detained in custody without being informed, as soon as may be, of the grounds for such arrest nor shall he be denied the right to consult, and to be defended by, a legal practitioner of his choice.\n(2) Every person who is arrested and detained in custody shall be produced before the nearest magistrate within a period of twenty-four hours of such arrest...",
    part: "Part III: Fundamental Rights",
    landmarkCases: [
      { caseName: "D.K. Basu v. State of West Bengal (1997)", caseSummary: "The Supreme Court laid down detailed guidelines that police must follow during arrest and detention to prevent custodial violence and protect the rights of the arrested person under Articles 21 and 22." }
    ],
    tags: ["Fundamental Rights", "Arrest and Detention", "Liberty"],
    limitationsAndExceptions: "The safeguards in clauses (1) and (2) are not available to enemy aliens or persons arrested under a preventive detention law. The grounds for preventive detention may not be disclosed if considered against the public interest.",
    relatedArticles: ["Article 20", "Article 21"],
  },
  {
    id: "Article 23",
    title: "Prohibition of traffic in human beings and forced labour",
    summary: "Prohibits human trafficking, 'begar' (forced labour without payment), and other similar forms of forced labour. Any contravention of this provision is a punishable offence.",
    detailedExplanation: "This article provides protection against exploitation. It prohibits traffic in human beings (buying and selling of people), bonded labour, and other forms of forced work without payment. Any violation is a punishable offense. Parliament has enacted laws like the Immoral Traffic (Prevention) Act, 1956, and the Bonded Labour System (Abolition) Act, 1976, to enforce this right.",
    fullText: "(1) Traffic in human beings and begar and other similar forms of forced labour are prohibited and any contravention of this provision shall be an offence punishable in accordance with law.\n(2) Nothing in this article shall prevent the State from imposing compulsory service for public purposes...",
    part: "Part III: Fundamental Rights",
    landmarkCases: [
        { caseName: "People's Union for Democratic Rights v. Union of India (1982)", caseSummary: "The court interpreted 'forced labour' broadly to include not just physical force but also compulsion arising from economic circumstances, such as paying less than the minimum wage." }
    ],
    tags: ["Fundamental Rights", "Exploitation", "Forced Labour"],
    limitationsAndExceptions: "The article provides an exception for the State to impose compulsory service for public purposes (like military service), provided it does not discriminate on grounds of religion, race, caste, or class.",
    relatedArticles: ["Article 24"],
  },
  {
    id: "Article 24",
    title: "Prohibition of employment of children in factories, etc.",
    summary: "Prohibits the employment of children below the age of fourteen years in any factory, mine, or other hazardous employment.",
    detailedExplanation: "This article provides for the protection of children from exploitation by prohibiting their employment in hazardous occupations. This is an absolute prohibition with no exceptions. This provision, along with Article 21A (Right to Education), forms the basis for laws against child labour, such as the Child Labour (Prohibition and Regulation) Act, 1986.",
    fullText: "No child below the age of fourteen years shall be employed to work in any factory or mine or engaged in any other hazardous employment.",
    part: "Part III: Fundamental Rights",
    landmarkCases: [
      { caseName: "M.C. Mehta v. State of Tamil Nadu (1996)", caseSummary: "The court gave exhaustive directions on eradicating child labour, including creating a Child Labour Rehabilitation Welfare Fund and ensuring education for the children involved." }
    ],
    tags: ["Fundamental Rights", "Exploitation", "Child Labour"],
    limitationsAndExceptions: "The prohibition is absolute for hazardous employment but did not originally cover non-hazardous work, which is now regulated by separate legislation.",
    relatedArticles: ["Article 21A", "Article 23", "Article 45"],
  },
  {
    id: "Article 25",
    title: "Freedom of conscience and free profession, practice and propagation of religion",
    summary: "Guarantees all persons the freedom of conscience and the right to freely profess, practice, and propagate religion, subject to public order, morality, and health.",
    detailedExplanation: "This article guarantees individual religious freedom. It includes freedom of conscience (inner belief, including atheism), the right to profess (declare beliefs), practice (perform rituals), and propagate (share beliefs). The Supreme Court has clarified that propagation does not mean the right to convert by force, fraud, or allurement. This freedom is not absolute and is subject to public order, morality, health, and other fundamental rights. The state can also regulate secular activities associated with religion and provide for social welfare and reform.",
    fullText: "(1) Subject to public order, morality and health and to the other provisions of this Part, all persons are equally entitled to freedom of conscience and the right freely to profess, practise and propagate religion.\n(2) Nothing in this article shall affect the operation of any existing law or prevent the State from making any law—\n(a) regulating or restricting any economic, financial, political or other secular activity which may be associated with religious practice...",
    part: "Part III: Fundamental Rights",
    landmarkCases: [
      { caseName: "Rev. Stainislaus v. State of Madhya Pradesh (1977)", caseSummary: "The Supreme Court held that the right to 'propagate' religion under Article 25 does not include a right to convert another person, but only to transmit or spread one's beliefs." },
      { caseName: "Indian Young Lawyers Association v. State of Kerala (2018)", caseSummary: "In the Sabarimala case, the court held that the exclusion of women of a certain age group violated their right to practice religion under Article 25, linking it to gender equality under Article 15." }
    ],
    tags: ["Fundamental Rights", "Religion", "Secularism"],
    limitationsAndExceptions: "This right is subject to public order, morality, health, and other Fundamental Rights. The State can regulate secular activities associated with religion and enact laws for social reform, like opening Hindu temples to all sections.",
    relatedArticles: ["Article 26", "Article 27", "Article 28"],
  },
  {
    id: "Article 26",
    title: "Freedom to manage religious affairs",
    summary: "Gives every religious denomination the right to establish and maintain religious institutions, manage its own religious affairs, and own and administer property.",
    detailedExplanation: "While Article 25 protects individual religious freedom, Article 26 protects the collective freedom of religious denominations. It grants them the right to establish and maintain institutions for religious and charitable purposes, manage their own religious affairs, own property, and administer that property in accordance with the law. This provides autonomy to religious groups.",
    fullText: "Subject to public order, morality and health, every religious denomination or any section thereof shall have the right—\n(a) to establish and maintain institutions for religious and charitable purposes;\n(b) to manage its own affairs in matters of religion;\n(c) to own and acquire movable and immovable property; and\n(d) to administer such property in accordance with law.",
    part: "Part III: Fundamental Rights",
    landmarkCases: [
        { caseName: "Shirur Mutt case (1954)", caseSummary: "This case was pivotal in defining a 'religious denomination' and distinguishing between essential religious matters (which are protected) and secular administrative activities (which can be regulated by the state)." }
    ],
    tags: ["Fundamental Rights", "Religion", "Secularism"],
    limitationsAndExceptions: "This right is also subject to public order, morality, and health. The right to administer property is 'in accordance with law,' meaning the State can enact secular laws to regulate the administration of such properties to prevent mismanagement.",
    relatedArticles: ["Article 25"],
  },
  {
    id: "Article 27",
    title: "Freedom as to payment of taxes for promotion of any particular religion",
    summary: "No person shall be compelled to pay any taxes for the promotion or maintenance of any particular religion.",
    detailedExplanation: "This article reinforces India's secular character by prohibiting the state from levying a tax and using public funds collected through taxes to promote or maintain any specific religion. It ensures that public money is not used to favor one religion over another. However, this does not prohibit the state from levying a fee for providing secular services to religious institutions, such as sanitation or security.",
    fullText: "No person shall be compelled to pay any taxes, the proceeds of which are specifically appropriated in payment of expenses for the promotion or maintenance of any particular religion or religious denomination.",
    part: "Part III: Fundamental Rights",
    landmarkCases: [],
    tags: ["Fundamental Rights", "Religion", "Secularism", "Taxation"],
    limitationsAndExceptions: "The article prohibits a 'tax' but not a 'fee'. A fee can be levied on religious institutions to cover the cost of secular services provided by the state. Voluntary donations are allowed.",
    relatedArticles: ["Article 25"],
  },
  {
    id: "Article 28",
    title: "Freedom as to attendance at religious instruction or religious worship in certain educational institutions",
    summary: "Prohibits religious instruction in state-run educational institutions. In other institutions, attendance is not compulsory without consent.",
    detailedExplanation: "This article outlines the rules for religious instruction in educational institutions. (1) Institutions wholly funded by the state are absolutely prohibited from imparting religious instruction. (2) Institutions administered by the state but established under a trust that requires religious instruction are exempt. (3) In state-recognized or state-aided institutions, no student can be compelled to attend religious instruction without their consent (or their guardian's if a minor).",
    fullText: "(1) No religious instruction shall be provided in any educational institution wholly maintained out of State funds.\n(2) Nothing in clause (1) shall apply to an educational institution which is administered by the State but has been established under any endowment or trust...\n(3) No person attending any educational institution recognised by the State or receiving aid...shall be required to take part in any religious instruction...",
    part: "Part III: Fundamental Rights",
    landmarkCases: [],
    tags: ["Fundamental Rights", "Religion", "Education", "Secularism"],
    limitationsAndExceptions: "The absolute prohibition applies only to institutions 'wholly maintained out of State funds'. The article allows for religious instruction in state-aided or recognized institutions, but makes attendance voluntary.",
    relatedArticles: ["Article 25", "Article 29", "Article 30"],
  },
  {
    id: "Article 29",
    title: "Protection of interests of minorities",
    summary: "Guarantees the right of any section of citizens to conserve their distinct language, script, or culture, and prohibits denial of admission to state-funded educational institutions on grounds of religion, race, caste, or language.",
    detailedExplanation: "This article provides cultural and educational rights. Clause (1) gives any section of citizens (not just minorities) the right to conserve their distinct language, script, or culture. Clause (2) is a specific non-discrimination right, ensuring that no citizen is denied admission into any educational institution maintained by the state or receiving state aid on grounds only of religion, race, caste, or language.",
    fullText: "(1) Any section of the citizens residing in the territory of India or any part thereof having a distinct language, script or culture of its own shall have the right to conserve the same.\n(2) No citizen shall be denied admission into any educational institution maintained by the State or receiving aid out of State funds on grounds only of religion, race, caste, language or any of them.",
    part: "Part III: Fundamental Rights",
    landmarkCases: [],
    tags: ["Fundamental Rights", "Minority Rights", "Education", "Culture"],
    limitationsAndExceptions: "The right in Clause (1) is available to any section of citizens, majority or minority. The non-discrimination right in Clause (2) applies only to state-maintained or state-aided institutions.",
    relatedArticles: ["Article 15", "Article 30"],
  },
  {
    id: "Article 30",
    title: "Right of minorities to establish and administer educational institutions",
    summary: "All religious or linguistic minorities have the right to establish and administer educational institutions of their choice. The State shall not discriminate in granting aid.",
    detailedExplanation: "This article provides a crucial right to religious and linguistic minorities to establish their own educational institutions to preserve their culture and language. The state is also barred from discriminating against these institutions when providing financial aid. Minorities recognized at the national level include Muslims, Christians, Sikhs, Buddhists, Parsis, and Jains. The Supreme Court has ruled that aided minority institutions can reserve up to 50% of seats for their community.",
    fullText: "(1) All minorities, whether based on religion or language, shall have the right to establish and administer educational institutions of their choice.\n(2) The State shall not, in granting aid to educational institutions, discriminate against any educational institution on the ground that it is under the management of a minority...",
    part: "Part III: Fundamental Rights",
    landmarkCases: [
      { caseName: "T.M.A. Pai Foundation v. State of Karnataka (2002)", caseSummary: "The court extensively interpreted Article 30, balancing the autonomy of minority institutions with the state's regulatory power to ensure educational standards." },
      { caseName: "St. Stephen’s College vs University of Delhi (1992)", caseSummary: "The Supreme Court ruled that minority institutions receiving government aid can reserve up to 50% of seats for students from their own community." }
    ],
    tags: ["Fundamental Rights", "Minority Rights", "Education"],
    limitationsAndExceptions: "The right to administer does not mean the right to maladminister. The State can impose reasonable regulations for academic standards and service conditions. Central universities established by an Act of Parliament (like AMU) cannot be granted minority status.",
    relatedArticles: ["Article 29"],
  },
  {
    id: "Article 31",
    title: "Right to Property (Repealed)",
    summary: "This article, which originally guaranteed the fundamental right to property, was repealed by the 44th Amendment Act in 1978. The right to property is now a legal right under Article 300-A.",
    detailedExplanation: "Originally a fundamental right, the Right to Property became a major obstacle for the government's land reform and socialist policies. After numerous amendments and legal battles, it was removed from Part III (Fundamental Rights) by the 44th Amendment in 1978. It was re-enacted as a constitutional right under Article 300-A in Part XII, which states that 'No person shall be deprived of his property save by authority of law.' This means the right is protected against arbitrary executive action but not against legislative action.",
    fullText: "[Repealed by the Constitution (Forty-fourth Amendment) Act, 1978]",
    part: "Part III: Fundamental Rights",
    landmarkCases: [],
    tags: ["Fundamental Rights", "Property", "Repealed"],
    limitationsAndExceptions: "This article has been repealed. The right to property is no longer a fundamental right but a constitutional/legal right under Article 300-A. Its violation cannot be directly challenged in the Supreme Court under Article 32.",
    relatedArticles: [],
  },
  {
    id: "Article 32",
    title: "Remedies for enforcement of rights conferred by this Part",
    summary: "Guarantees the right to move the Supreme Court for the enforcement of Fundamental Rights. The Supreme Court can issue five types of writs: habeas corpus, mandamus, prohibition, certiorari, and quo warranto.",
    detailedExplanation: "Dr. B.R. Ambedkar called this article the 'heart and soul' of the Constitution. It is a fundamental right that guarantees an effective remedy for the violation of other fundamental rights. It designates the Supreme Court as the protector of these rights, empowering it to issue five types of writs: Habeas Corpus (release from unlawful detention), Mandamus (commanding a public official to act), Prohibition (stopping a lower court from exceeding jurisdiction), Certiorari (quashing an order of a lower court), and Quo Warranto (inquiring into the legality of a person's claim to a public office).",
    fullText: "(1) The right to move the Supreme Court by appropriate proceedings for the enforcement of the rights conferred by this Part is guaranteed.\n(2) The Supreme Court shall have power to issue directions or orders or writs, including writs in the nature of habeas corpus, mandamus, prohibition, quo warranto and certiorari...",
    part: "Part III: Fundamental Rights",
    landmarkCases: [
      { caseName: "L. Chandra Kumar v. Union of India (1997)", caseSummary: "The Supreme Court held that the power of judicial review of the High Courts under Article 226 and the Supreme Court under Article 32 is a 'basic feature' of the Constitution." }
    ],
    tags: ["Fundamental Rights", "Judicial Review", "Writs", "Supreme Court"],
    limitationsAndExceptions: "This right can be suspended by the President during a National Emergency under Article 359 (except for violations of Articles 20 and 21). The remedy under Article 32 is available only for the violation of Fundamental Rights.",
    relatedArticles: ["Article 13", "Article 226 (related power of High Courts)"],
    fillInTheBlanks: [{ question: "The Supreme Court shall have power to issue directions or orders or ____...", answer: "writs" }]
  },
  {
    id: "Article 33",
    title: "Power of Parliament to modify the rights conferred by this Part in their application to Forces, etc.",
    summary: "Allows Parliament to restrict or abrogate the fundamental rights of members of the Armed Forces, paramilitary forces, police, and intelligence agencies to ensure discipline and proper discharge of duties.",
    detailedExplanation: "This article grants Parliament the power to make laws that limit the fundamental rights of personnel in specific crucial services like the armed forces and intelligence agencies. The purpose is to ensure discipline and duty, which are vital for national security. Rights that can be restricted include freedom of speech, association, and protest. Any law made under this article cannot be challenged in court for violating fundamental rights.",
    fullText: "Parliament may, by law, determine to what extent any of the rights conferred by this Part shall, in their application to,—\n(a) the members of the Armed Forces; or\n(b) the members of the Forces charged with the maintenance of public order...",
    part: "Part III: Fundamental Rights",
    landmarkCases: [],
    tags: ["Fundamental Rights", "Parliament", "Armed Forces"],
    limitationsAndExceptions: "This is an explicit exception to Fundamental Rights. The power to make such restrictive laws is vested exclusively with the Parliament, not state legislatures. Laws made under this article cannot be challenged for violating Part III rights.",
    relatedArticles: ["Article 34"],
  },
  {
    id: "Article 34",
    title: "Restriction on rights conferred by this Part while martial law is in force in any area",
    summary: "Restricts fundamental rights while martial law is in force. It empowers Parliament to indemnify any government servant for acts done to maintain or restore order.",
    detailedExplanation: "This article provides for the restriction of fundamental rights when martial law (military rule) is in force in any area. While the Constitution does not define 'martial law,' it is invoked in extraordinary situations like war, invasion, or armed rebellion. This article empowers Parliament to pass an 'Act of Indemnity' to legally protect officials from legal action for acts committed while maintaining order under martial law, even if those acts violated fundamental rights.",
    fullText: "Notwithstanding anything in the foregoing provisions of this Part, Parliament may by law indemnify any person in the service of the Union or of a State... in respect of any act done by him in connection with the maintenance or restoration of order in any area within the territory of India where martial law was in force...",
    part: "Part III: Fundamental Rights",
    landmarkCases: [],
    tags: ["Fundamental Rights", "Parliament", "Martial Law"],
    limitationsAndExceptions: "This is an explicit exception to Fundamental Rights, applicable only in areas where martial law is in force. It effectively suspends judicial remedy for actions validated by Parliament.",
    relatedArticles: ["Article 33"],
  },
  {
    id: "Article 35",
    title: "Legislation to give effect to the provisions of this Part",
    summary: "Gives Parliament, not state legislatures, the exclusive power to make laws for prescribing punishment for offences related to certain fundamental rights.",
    detailedExplanation: "This article ensures uniformity in legislation across India regarding certain fundamental rights. It grants Parliament exclusive power to make laws prescribing punishments for acts declared as offences under Part III, such as untouchability (Article 17) and forced labour (Article 23). It also gives Parliament exclusive power to legislate on matters under Articles 16(3) (residence requirements for jobs), 32(3) (empowering other courts to issue writs), 33 (restricting rights of armed forces), and 34 (martial law).",
    fullText: "Notwithstanding anything in this Constitution,—\n(a) Parliament shall have, and the Legislature of a State shall not have, power to make laws—\n(i) with respect to any of the matters which under clause (3) of article 16, clause (3) of article 32, article 33 and article 34... and\n(ii) for prescribing punishment for those acts which are declared to be offences under this Part...",
    part: "Part III: Fundamental Rights",
    landmarkCases: [],
    tags: ["Fundamental Rights", "Parliament"],
    limitationsAndExceptions: "This article limits the legislative power of State Legislatures on certain matters of fundamental rights to ensure national uniformity.",
    relatedArticles: ["Article 17", "Article 23"],
  },
  {
    id: "Article 36",
    title: "Definition",
    summary: "Defines 'the State' for Part IV (Directive Principles) as having the same meaning as in Part III (Fundamental Rights).",
    detailedExplanation: "This article states that for the purpose of the Directive Principles of State Policy (DPSP), the term 'State' has the same meaning as defined in Article 12. This means the directives are aimed at the Union and State governments, Parliament and State Legislatures, and all local or other authorities. This ensures that the responsibility to implement these guiding principles is wide-ranging, covering all levels of government.",
    fullText: "In this Part, unless the context otherwise requires, 'the State' has the same meaning as in Part III.",
    part: "Part IV: Directive Principles of State Policy",
    landmarkCases: [],
    tags: ["DPSP", "State", "Definition"],
    limitationsAndExceptions: "This is a definitional article. The main limitation of all DPSPs is their non-justiciable nature as defined in Article 37.",
    relatedArticles: ["Article 12", "Article 37"],
  },
  {
    id: "Article 37",
    title: "Application of the principles contained in this part",
    summary: "The Directive Principles are not enforceable by any court, but are fundamental in the governance of the country, and it is the duty of the State to apply them in making laws.",
    detailedExplanation: "This article clarifies the nature of Directive Principles. They are not justiciable, meaning citizens cannot go to court to compel the government to implement them. However, they are declared 'fundamental in the governance of the country' and impose a moral 'duty' on the State to apply them when making laws. They serve as a moral compass for the government and a benchmark for voters to evaluate its performance.",
    fullText: "The provisions contained in this Part shall not be enforceable by any court, but the principles therein laid down are nevertheless fundamental in the governance of the country and it shall be the duty of the State to apply these principles in making laws.",
    part: "Part IV: Directive Principles of State Policy",
    landmarkCases: [
        { caseName: "Minerva Mills v. Union of India (1980)", caseSummary: "The court held that the Indian Constitution is founded on the balance between Fundamental Rights and Directive Principles. They are like two wheels of a chariot, and one cannot be given primacy over the other, establishing the doctrine of 'harmony and balance'." }
    ],
    tags: ["DPSP", "Governance", "Justiciability"],
    limitationsAndExceptions: "This article explicitly states that DPSPs are 'not enforceable by any court.' They are fundamental guidelines that impose a moral, not legal, duty on the State.",
    relatedArticles: ["Article 36"],
  },
  {
    id: "Article 38",
    title: "State to secure a social order for the promotion of welfare of the people",
    summary: "The State shall strive to promote the welfare of the people by securing a social order based on social, economic, and political justice, and shall minimise inequalities in income, status, facilities, and opportunities.",
    detailedExplanation: "This article embodies the vision of a welfare state. It directs the state to build a social order where justice—social, economic, and political—is central to all institutions. Clause (2), added by the 44th Amendment, further directs the state to reduce inequalities in income, status, and opportunities, not just among individuals but also among groups and regions. This article sets the broad socio-economic goals of the nation.",
    fullText: "(1) The State shall strive to promote the welfare of the people by securing and protecting as effectively as it may a social order in which justice, social, economic and political, shall inform all the institutions of the national life.\n(2) The State shall, in particular, strive to minimise the inequalities in income, and endeavour to eliminate inequalities in status, facilities and opportunities...",
    part: "Part IV: Directive Principles of State Policy",
    landmarkCases: [],
    tags: ["DPSP", "Welfare State", "Social Justice", "Equality"],
    limitationsAndExceptions: "As a DPSP, this is a non-justiciable directive that sets aspirational goals for the State.",
    relatedArticles: ["Article 14", "Article 39"],
  },
  {
    id: "Article 39",
    title: "Certain principles of policy to be followed by the State",
    summary: "Outlines principles for the State, including securing adequate means of livelihood, equitable distribution of resources, preventing concentration of wealth, equal pay for equal work, and protecting the health of workers and children.",
    detailedExplanation: "This article lists several key socio-economic goals. It directs state policy towards securing: (a) adequate means of livelihood for all citizens; (b) equitable distribution of community resources; (c) preventing the concentration of wealth; (d) equal pay for equal work for men and women; (e) protecting the health of workers and children from abuse and exploitation; and (f) ensuring children develop in a healthy manner.",
    fullText: "The State shall, in particular, direct its policy towards securing—\n(a) that the citizens, men and women equally, have the right to an adequate means of livelihood;\n(b) that the ownership and control of the material resources of the community are so distributed as best to subserve the common good;\n(c) that the operation of the economic system does not result in the concentration of wealth...\n(d) that there is equal pay for equal work for both men and women...",
    part: "Part IV: Directive Principles of State Policy",
    landmarkCases: [
      { caseName: "Randhir Singh v. Union of India (1982)", caseSummary: "The court held that 'equal pay for equal work,' though a DPSP, is a constitutional goal and can be enforced through the fundamental rights of equality in cases of arbitrary discrimination." }
    ],
    tags: ["DPSP", "Social Justice", "Economic Justice", "Equality"],
    limitationsAndExceptions: "These are non-justiciable principles, though courts have sometimes enforced principles like 'equal pay for equal work' by linking them to Fundamental Rights.",
    relatedArticles: ["Article 14", "Article 16", "Article 38"],
  },
  {
    id: "Article 39A",
    title: "Equal justice and free legal aid",
    summary: "The State shall provide free legal aid to ensure that justice is not denied to any citizen due to economic or other disabilities.",
    detailedExplanation: "Added by the 42nd Amendment, this DPSP is crucial for ensuring access to justice. It directs the state to provide free legal aid to the poor and weaker sections so that justice is not denied due to economic hardship. This led to the enactment of the Legal Services Authorities Act, 1987, establishing NALSA and Lok Adalats to provide free legal services.",
    fullText: "The State shall secure that the operation of the legal system promotes justice, on a basis of equal opportunity, and shall, in particular, provide free legal aid... to ensure that opportunities for securing justice are not denied to any citizen by reason of economic or other disabilities.",
    part: "Part IV: Directive Principles of State Policy",
    landmarkCases: [
      { caseName: "Hussainara Khatoon v. Home Secretary, State of Bihar (1979)", caseSummary: "The Supreme Court held that the right to free legal aid is an essential part of a 'reasonable, fair and just' procedure under Article 21, effectively elevating this DPSP to a fundamental right in criminal cases." }
    ],
    tags: ["DPSP", "Social Justice", "Legal Aid"],
    limitationsAndExceptions: "While this is a DPSP, the Supreme Court has made the right to free legal aid a fundamental right in criminal proceedings by linking it to Article 21.",
    relatedArticles: ["Article 14", "Article 21"],
  },
  {
    id: "Article 40",
    title: "Organisation of village panchayats",
    summary: "The State shall take steps to organise village panchayats and empower them to function as units of self-government.",
    detailedExplanation: "This is a Gandhian principle reflecting the vision of democratic decentralization. It directs the state to establish village panchayats as units of local self-government. This DPSP was given practical effect by the 73rd Constitutional Amendment Act of 1992, which granted constitutional status to Panchayati Raj Institutions (PRIs) and established a three-tier system of local governance in rural India.",
    fullText: "The State shall take steps to organise village panchayats and endow them with such powers and authority as may be necessary to enable them to function as units of self-government.",
    part: "Part IV: Directive Principles of State Policy",
    landmarkCases: [],
    tags: ["DPSP", "Panchayats", "Gandhian Principles", "Governance"],
    limitationsAndExceptions: "This directive was non-enforceable until the 73rd Amendment made Panchayats a constitutional mandate. The extent of powers devolved to panchayats still varies between states.",
    relatedArticles: [],
  },
  {
    id: "Article 41",
    title: "Right to work, to education and to public assistance in certain cases",
    summary: "Within its economic capacity, the State shall make effective provision for securing the right to work, to education, and to public assistance in cases of unemployment, old age, sickness, and disablement.",
    detailedExplanation: "This article directs the state to create a social safety net, but makes the right to work, education, and public assistance subject to the 'economic capacity and development' of the state. It is a goal to be achieved progressively. Schemes like MGNREGA, old-age pensions, and disability benefits are based on this directive.",
    fullText: "The State shall, within the limits of its economic capacity and development, make effective provision for securing the right to work, to education and to public assistance in cases of unemployment, old age, sickness and disablement, and in other cases of undeserved want.",
    part: "Part IV: Directive Principles of State Policy",
    landmarkCases: [],
    tags: ["DPSP", "Welfare State", "Social Security"],
    limitationsAndExceptions: "The implementation is explicitly limited by the 'economic capacity and development' of the State, making these rights aspirational rather than legally enforceable.",
    relatedArticles: ["Article 21A", "Article 42", "Article 43"],
  },
  {
    id: "Article 42",
    title: "Provision for just and humane conditions of work and maternity relief",
    summary: "The State shall make provision for securing just and humane conditions of work and for maternity relief.",
    detailedExplanation: "This directive focuses on labour welfare, mandating the state to ensure safe, fair, and humane working conditions. It specifically highlights the need for maternity relief for working women. Laws like the Maternity Benefit Act, 1961, and various factory safety regulations are legislative actions taken in pursuance of this article.",
    fullText: "The State shall make provision for securing just and humane conditions of work and for maternity relief.",
    part: "Part IV: Directive Principles of State Policy",
    landmarkCases: [],
    tags: ["DPSP", "Labour Rights", "Welfare State", "Maternity"],
    limitationsAndExceptions: "This is a non-justiciable directive whose implementation depends on legislation passed by the State.",
    relatedArticles: ["Article 41", "Article 43"],
  },
  {
    id: "Article 43",
    title: "Living wage, etc., for workers",
    summary: "The State shall endeavour to secure a living wage, a decent standard of life, and full enjoyment of leisure for all workers, and promote cottage industries in rural areas.",
    detailedExplanation: "This article directs the state to strive for a 'living wage'—more than a minimum wage—sufficient for a decent standard of life for workers and their families. It also emphasizes leisure and cultural opportunities. Additionally, as a Gandhian principle, it directs the state to promote cottage industries on an individual or cooperative basis in rural areas.",
    fullText: "The State shall endeavour to secure, by suitable legislation or economic organisation or in any other way, to all workers, agricultural, industrial or otherwise, work, a living wage, conditions of work ensuring a decent standard of life and full enjoyment of leisure and social and cultural opportunities and, in particular, the State shall endeavour to promote cottage industries on an individual or co-operative basis in rural areas.",
    part: "Part IV: Directive Principles of State Policy",
    landmarkCases: [],
    tags: ["DPSP", "Labour Rights", "Welfare State", "Gandhian Principles"],
    limitationsAndExceptions: "A 'living wage' is an aspirational goal, not a legally enforceable right. The State is only required to 'endeavour' to secure it.",
    relatedArticles: ["Article 41", "Article 42"],
  },
  {
    id: "Article 43A",
    title: "Participation of workers in management of industries",
    summary: "The State shall take steps to secure the participation of workers in the management of undertakings, establishments or other organisations engaged in any industry.",
    detailedExplanation: "Added by the 42nd Amendment, this article reflects a socialist ideal inspired by the Janata Party government. It directs the state to ensure that workers are not passive employees but active participants in the decision-making processes of industries. The idea is that their input is vital for better management and welfare. Many Public Sector Units (PSUs) and some private companies include worker representatives on their management boards or committees.",
    fullText: "The State shall take steps, by suitable legislation or in any other way, to secure the participation of workers in the management of undertakings, establishments or other organizations engaged in any industry.",
    part: "Part IV: Directive Principles of State Policy",
    landmarkCases: [],
    tags: ["DPSP", "Labour Rights", "Industrial Democracy"],
    limitationsAndExceptions: "This is a non-justiciable directive. The extent and nature of worker participation are determined by specific legislation or company policy.",
    relatedArticles: ["Article 43"],
  },
  {
    id: "Article 43B",
    title: "Promotion of co-operative societies",
    summary: "The State shall endeavour to promote voluntary formation, autonomous functioning, democratic control and professional management of co-operative societies.",
    detailedExplanation: "Added by the 97th Amendment in 2011, this article aims to strengthen the co-operative movement in India. It directs the state to promote co-operatives that are voluntary, autonomous, democratically controlled, and professionally managed. This amendment granted constitutional recognition to co-operatives and aimed to unify co-operative laws across states.",
    fullText: "The State shall endeavour to promote voluntary formation, autonomous functioning, democratic control and professional management of co-operative societies.",
    part: "Part IV: Directive Principles of State Policy",
    landmarkCases: [],
    tags: ["DPSP", "Co-operative Societies", "Governance"],
    limitationsAndExceptions: "This is a non-justiciable directive guiding state policy towards co-operatives.",
    relatedArticles: [],
  },
  {
    id: "Article 44",
    title: "Uniform civil code for the citizens",
    summary: "The State shall endeavour to secure for the citizens a uniform civil code throughout the territory of India.",
    detailedExplanation: "This article directs the state to strive for a Uniform Civil Code (UCC), which would replace diverse personal laws based on religion with a single set of secular civil laws governing matters like marriage, divorce, inheritance, and adoption. The goal is to promote national integration and gender justice. It remains a highly debated DPSP. The Supreme Court has repeatedly urged the government to implement it, but it has not been enacted due to political sensitivities and concerns about religious freedom.",
    fullText: "The State shall endeavour to secure for the citizens a uniform civil code throughout the territory of India.",
    part: "Part IV: Directive Principles of State Policy",
    landmarkCases: [
      { caseName: "Mohd. Ahmed Khan v. Shah Bano Begum (1985)", caseSummary: "The Supreme Court's decision to grant maintenance to a divorced Muslim woman under secular law sparked a major political controversy and highlighted the need for a UCC to ensure gender justice." },
      { caseName: "Sarla Mudgal v. Union of India (1995)", caseSummary: "The Supreme Court again lamented the lack of a UCC, stating it is necessary for national integration." }
    ],
    tags: ["DPSP", "Uniform Civil Code", "Secularism", "Gender Justice"],
    limitationsAndExceptions: "This is a non-justiciable directive. Its implementation involves a perceived conflict between the goal of uniformity and the fundamental right to freedom of religion (Article 25).",
    relatedArticles: ["Article 14", "Article 15", "Article 25"],
  },
  {
    id: "Article 45",
    title: "Provision for early childhood care and education to children below the age of six years",
    summary: "The State shall endeavour to provide early childhood care and education for all children until they complete the age of six years.",
    detailedExplanation: "Originally, this article was for education up to 14 years. After the 86th Amendment made education a fundamental right under Article 21A (for ages 6-14), Article 45 was amended to its current form. It now directs the state to focus on early childhood care and education (ECCE) for children below six. This forms the basis for programmes like the Integrated Child Development Services (ICDS) and Anganwadis.",
    fullText: "The State shall endeavour to provide early childhood care and education for all children until they complete the age of six years.",
    part: "Part IV: Directive Principles of State Policy",
    landmarkCases: [],
    tags: ["DPSP", "Education", "Welfare State", "Children"],
    limitationsAndExceptions: "This is now a non-enforceable directive for early childhood care (age 0-6), while education for ages 6-14 is a legally enforceable fundamental right under Article 21A.",
    relatedArticles: ["Article 21A", "Article 24"],
  },
  {
    id: "Article 46",
    title: "Promotion of educational and economic interests of Scheduled Castes, Scheduled Tribes and other weaker sections",
    summary: "The State shall promote with special care the educational and economic interests of the weaker sections, particularly SCs and STs, and protect them from social injustice and exploitation.",
    detailedExplanation: "This is a key directive for social justice, imposing a duty on the state to promote the educational and economic well-being of the most disadvantaged sections of society. It specifically names Scheduled Castes and Scheduled Tribes and also includes other weaker sections. It mandates the state to protect them from social injustice and all forms of exploitation. Reservation policies and various welfare schemes are rooted in this directive.",
    fullText: "The State shall promote with special care the educational and economic interests of the weaker sections of the people, and, in particular, of the Scheduled Castes and the Scheduled Tribes, and shall protect them from social injustice and all forms of exploitation.",
    part: "Part IV: Directive Principles of State Policy",
    landmarkCases: [],
    tags: ["DPSP", "Social Justice", "Reservation", "SC/ST"],
    limitationsAndExceptions: "This non-justiciable directive provides the constitutional justification for affirmative action policies, which are themselves subject to legal limits (e.g., the 50% cap on reservations).",
    relatedArticles: ["Article 15", "Article 16"],
  },
  {
    id: "Article 47",
    title: "Duty of the State to raise the level of nutrition and the standard of living and to improve public health",
    summary: "The State shall regard raising nutrition levels, the standard of living, and public health as its primary duties, and endeavour to prohibit intoxicating drinks and drugs.",
    detailedExplanation: "This directive sets public health and nutrition as primary duties of the state. It is the basis for food security schemes (like PDS) and nutritional programmes (like Mid-Day Meal). The second part, a Gandhian principle, directs the state to work towards the prohibition of alcohol and harmful drugs, except for medicinal purposes. Prohibition policies in some states are based on this directive.",
    fullText: "The State shall regard the raising of the level of nutrition and the standard of living of its people and the improvement of public health as among its primary duties and, in particular, the State shall endeavour to bring about prohibition of the consumption except for medicinal purposes of intoxicating drinks and of drugs which are injurious to health.",
    part: "Part IV: Directive Principles of State Policy",
    landmarkCases: [],
    tags: ["DPSP", "Public Health", "Welfare State", "Gandhian Principles"],
    limitationsAndExceptions: "The duty to improve public health is a primary but non-justiciable duty. The directive to prohibit intoxicating drinks is an 'endeavour' and not mandatory.",
    relatedArticles: ["Article 21"],
  },
  {
    id: "Article 48",
    title: "Organisation of agriculture and animal husbandry",
    summary: "The State shall endeavour to organise agriculture and animal husbandry on modern lines and prohibit the slaughter of cows, calves, and other milch and draught cattle.",
    detailedExplanation: "This directive has two parts. The first directs the state to modernise agriculture and animal husbandry. The second, a Gandhian principle, directs the state to prohibit the slaughter of cows and other useful cattle. This reflects both economic considerations (importance of cattle in an agrarian economy) and cultural sentiments. It is the basis for cattle protection laws enacted by various states.",
    fullText: "The State shall endeavour to organise agriculture and animal husbandry on modern and scientific lines and shall, in particular, take steps for preserving and improving the breeds, and prohibiting the slaughter, of cows and calves and other milch and draught cattle.",
    part: "Part IV: Directive Principles of State Policy",
    landmarkCases: [
      { caseName: "State of Gujarat v. Mirzapur Moti Kureshi Kassab Jamat (2005)", caseSummary: "The Supreme Court upheld a law imposing a total ban on the slaughter of cows and their progeny, arguing it was a reasonable restriction in the interest of the general public." }
    ],
    tags: ["DPSP", "Agriculture", "Gandhian Principles", "Animal Husbandry"],
    limitationsAndExceptions: "This is a non-justiciable directive. Laws based on this article must still respect the fundamental rights of citizens, such as the right to practice a profession (Article 19(1)(g)).",
    relatedArticles: ["Article 48A"],
  },
   {
    id: "Article 48A",
    title: "Protection and improvement of environment and safeguarding of forests and wild life",
    summary: "The State shall endeavour to protect and improve the environment and to safeguard the forests and wildlife of the country.",
    detailedExplanation: "Added by the 42nd Amendment in 1976, this article places a directive duty on the State to protect the environment. It was introduced to address the growing environmental crisis due to deforestation and pollution. Following this directive, India enacted several key environmental laws, including the Wildlife (Protection) Act 1972, Water (Prevention and Control of Pollution) Act 1974, Forest (Conservation) Act 1980, Air (Prevention and Control of Pollution) Act 1981, and the umbrella Environment (Protection) Act 1986.",
    fullText: "The State shall endeavour to protect and improve the environment and to safeguard the forests and wildlife of the country.",
    part: "Part IV: Directive Principles of State Policy",
    landmarkCases: [],
    tags: ["DPSP", "Environment", "Wildlife", "Forests"],
    limitationsAndExceptions: "This is a non-justiciable directive, but it forms the basis for a robust framework of environmental legislation in India. It is complemented by the fundamental duty of citizens under Article 51A(g) to protect the environment.",
    relatedArticles: ["Article 48", "Article 51A"],
  },
  {
    id: "Article 49",
    title: "Protection of monuments and places and objects of national importance",
    summary: "It is the obligation of the State to protect every monument, place, or object of artistic or historic interest declared to be of national importance.",
    detailedExplanation: "This directive imposes a duty on the state to protect India's cultural heritage. It mandates the protection of monuments and objects declared to be of national importance from destruction, disfigurement, or export. The Archaeological Survey of India (ASI) and laws like the Ancient Monuments and Archaeological Sites and Remains Act, 1958, are the primary instruments for fulfilling this directive.",
    fullText: "It shall be the obligation of the State to protect every monument or place or object of artistic or historic interest, declared by or under law made by Parliament to be of national importance, from spoliation, disfigurement, destruction, removal, disposal or export, as the case may be.",
    part: "Part IV: Directive Principles of State Policy",
    landmarkCases: [],
    tags: ["DPSP", "Culture", "Heritage", "Monuments"],
    limitationsAndExceptions: "This obligation applies specifically to monuments and objects that have been declared of 'national importance' by law.",
    relatedArticles: ["Article 51A"],
  },
  {
    id: "Article 50",
    title: "Separation of judiciary from executive",
    summary: "The State shall take steps to separate the judiciary from the executive in the public services of the State.",
    detailedExplanation: "This DPSP is crucial for ensuring the independence and impartiality of the judiciary. It directs the state to separate judicial functions from executive functions to prevent bias and arbitrary action. This principle has been largely implemented in the criminal justice system through the Code of Criminal Procedure (CrPC), 1973, which separated judicial magistrates (under the High Court) from executive magistrates (under the state government). Judicial independence is now considered a basic feature of the Constitution.",
    fullText: "The State shall take steps to separate the judiciary from the executive in the public services of the State.",
    part: "Part IV: Directive Principles of State Policy",
    landmarkCases: [],
    tags: ["DPSP", "Judiciary", "Separation of Powers", "Governance"],
    limitationsAndExceptions: "While largely implemented, some overlap in administrative functions can still exist. The principle is a non-justiciable directive.",
    relatedArticles: [],
  },
  {
    id: "Article 51",
    title: "Promotion of international peace and security",
    summary: "The State shall endeavour to promote international peace, maintain just relations between nations, foster respect for international law, and encourage settlement of international disputes by arbitration.",
    detailedExplanation: "This article outlines India's foreign policy principles. It directs the state to: (a) promote international peace, (b) maintain just relations with other nations, (c) foster respect for international law and treaties, and (d) encourage settlement of disputes by arbitration. These principles have guided India's policy of non-alignment, its role in the UN, and its commitment to peaceful coexistence, as seen in the Panchsheel Agreement.",
    fullText: "The State shall endeavour to—\n(a) promote international peace and security;\n(b) maintain just and honourable relations between nations;\n(c) foster respect for international law and treaty obligations...\n(d) encourage settlement of international disputes by arbitration.",
    part: "Part IV: Directive Principles of State Policy",
    landmarkCases: [
      { caseName: "Vishaka v. State of Rajasthan (1997)", caseSummary: "The Supreme Court relied on international conventions to frame guidelines against sexual harassment, giving effect to the principle of fostering respect for international law in Article 51(c)." }
    ],
    tags: ["DPSP", "Foreign Policy", "International Law", "Peace"],
    limitationsAndExceptions: "These are non-justiciable guiding principles for foreign policy. In case of a direct conflict, domestic law prevails over international law.",
    relatedArticles: [],
  },
  {
    id: "Article 51A",
    title: "Fundamental duties",
    summary: "Lists eleven fundamental duties of every citizen, including abiding by the Constitution, promoting harmony, protecting public property, and providing educational opportunities for children.",
    detailedExplanation: "Added by the 42nd Amendment (1976) and expanded by the 86th Amendment (2002), this article lists the duties of citizens. These include respecting the Constitution, National Flag, and Anthem; cherishing the ideals of the freedom struggle; protecting India's sovereignty; promoting harmony; preserving our culture; protecting the environment; developing scientific temper; safeguarding public property; and striving for excellence. The eleventh duty mandates parents to provide educational opportunities for their children aged 6-14. These duties are non-justiciable but serve as a moral compass for citizens.",
    fullText: "It shall be the duty of every citizen of India—\n(a) to abide by the Constitution and respect its ideals and institutions, the National Flag and the National Anthem;\n(b) to cherish and follow the noble ideals which inspired our national struggle for freedom;\n(c) to uphold and protect the sovereignty, unity and integrity of India;\n(d) to defend the country and render national service when called upon to do so;\n(e) to promote harmony and the spirit of common brotherhood...;\n(f) to value and preserve the rich heritage of our composite culture;\n(g) to protect and improve the natural environment...;\n(h) to develop the scientific temper, humanism and the spirit of inquiry and reform;\n(i) to safeguard public property and to abjure violence;\n(j) to strive towards excellence...;\n(k) who is a parent or guardian to provide opportunities for education to his child... between the age of six and fourteen years.",
    part: "Part IVA: Fundamental Duties",
    landmarkCases: [
      { caseName: "AIIMS Students' Union v. AIIMS (2002)", caseSummary: "The Supreme Court held that Fundamental Duties, though non-enforceable, can be used to interpret ambiguous statutes and determine the reasonableness of legislative restrictions on fundamental rights." }
    ],
    tags: ["Fundamental Duties", "Citizenship", "Responsibility"],
    limitationsAndExceptions: "Fundamental Duties are non-justiciable, meaning they are not directly enforceable by courts and carry no legal penalty for violation unless a specific law makes such a violation an offence.",
    relatedArticles: ["Article 21A", "Article 48A", "Article 49"],
    fillInTheBlanks: [{ question: "It shall be the ____ of every citizen of India to abide by the Constitution.", answer: "duty" }]
  }
];
