import { Article } from '../types';

export const CONSTITUTION_ARTICLES: Article[] = [
  {
    id: "Intro-Making",
    title: "Making of the Constitution",
    summary: "The journey of creating the Indian Constitution, from the initial demand by M. N. Roy in 1934 to its final adoption on 26th November 1949, guided by the Cabinet Mission of 1946.",
    detailedExplanation: "The Constitution is the fundamental law of the country, a legal written document establishing the Legislature, Executive, and Judiciary. The first demand for a Constituent Assembly was made in 1934 by M. N. Roy and reiterated by C. Rajagopalachari in 1935. The first complete plan for its formation came with the Cabinet Mission of 1946. The Assembly was formed on 6 December 1946, based on the French model, with its first meeting on 9 December 1946. Sachchidananda Sinha was the temporary chairman, with Dr. Rajendra Prasad elected as the permanent Chairman on 11 December 1946. The 'Objectives Resolution,' laying down the Constitution's philosophy, was introduced by Pandit Jawaharlal Nehru on 13 December 1946. The Drafting Committee, chaired by Dr. B. R. Ambedkar, was set up on 29 August 1947. The entire process took 2 years, 11 months, and 18 days, with the Constitution being adopted on 26th November 1949 and coming into force on 26th January 1950.",
    fullText: "Key Facts:\n- First Demand: M. N. Roy (1934)\n- Formation Plan: Cabinet Mission (1946)\n- First Meeting: 9 December 1946\n- Permanent Chairman: Dr. Rajendra Prasad\n- Constitutional Advisor: B. N. Rau\n- Drafting Committee Chairman: Dr. B. R. Ambedkar\n- Adopted: 26th November 1949\n- Enforced: 26th January 1950",
    part: "Introduction",
    landmarkCases: [],
    tags: ["History", "Constituent Assembly", "Drafting"],
    limitationsAndExceptions: "This historical overview provides context for the legal articles that follow.",
    relatedArticles: ["Intro-Features", "Preamble"],
    fillInTheBlanks: [
      { question: "The demand for a Constituent Assembly was first made in ____ by M. N. Roy.", answer: "1934" },
      { question: "The Constituent Assembly took 2 years, 11 months, and ____ days to complete the Constitution.", answer: "18" }
    ]
  },
  {
    id: "Intro-Features",
    title: "Features of the Constitution",
    summary: "An overview of the key characteristics of the Indian Constitution, including its status as the world's largest, its blend of flexibility and rigidity, and its establishment of a secular, parliamentary democracy with single citizenship.",
    detailedExplanation: "The Indian Constitution is the largest in the world, originally with 22 Parts, 395 Articles, and 8 Schedules. Today, it has grown to 25 Parts, over 450 Articles, and 12 Schedules. The framers examined nearly 60 different constitutions, borrowing heavily (nearly 250 provisions) from the Government of India Act, 1935. Key borrowed concepts include Fundamental Rights and Judicial Review from the U.S. Constitution and Directive Principles from the Irish Constitution. The Constitution is both flexible and rigid, with amendments governed by Article 368 to preserve its basic structure. It establishes a Parliamentary Democracy, a Three-Tier Government (Panchayati Raj), and Single Citizenship. As a Secular State, India has no official religion and ensures equal respect for all. The voting age was reduced from 21 to 18 by the 61st Constitutional Amendment in 1989.",
    fullText: "Key Features:\n- Largest Constitution in the world.\n- Partially flexible, partially rigid.\n- Parliamentary Democracy.\n- Three-Tier Government.\n- Single Citizenship.\n- Secular State (positive secularism).\n- Voting age reduced to 18 by the 61st Amendment (1989).",
    part: "Introduction",
    landmarkCases: [],
    tags: ["Features", "Secularism", "Democracy", "Citizenship"],
    limitationsAndExceptions: "The features provide the foundational principles upon which the specific articles are built.",
    relatedArticles: ["Intro-Making", "Preamble"],
    fillInTheBlanks: [
      { question: "The voting age was reduced to 18 years by the ____ Constitutional Amendment (1989).", answer: "61st" },
      { question: "Fundamental Rights and Judicial Review were borrowed from the ____ Constitution.", answer: "U.S." }
    ]
  },
  {
    id: "Preamble",
    title: "The Preamble",
    summary: "The Preamble summarizes the essence of the Constitution, declaring India as a Sovereign, Socialist, Secular, Democratic Republic and securing Justice, Liberty, Equality, and Fraternity for its citizens.",
    detailedExplanation: "The Preamble acts as the introduction and philosophy of the Constitution. It describes the nation with five guiding words: Sovereign, Socialist, Secular, Democratic, and Republic. The terms 'Socialist' and 'Secular' were added by the 42nd Amendment in 1976. 'Sovereign' means India is fully independent. 'Republic' means the head of state is elected. It resolves to grant four assurances to all citizens: Justice (Social, Economic, Political), Liberty (of Thought, Expression, Belief, Faith, Worship), Equality (of Status and Opportunity), and Fraternity (assuring individual dignity and national unity).",
    fullText: "WE, THE PEOPLE OF INDIA, having solemnly resolved to constitute India into a SOVEREIGN SOCIALIST SECULAR DEMOCRATIC REPUBLIC and to secure to all its citizens:\nJUSTICE, social, economic and political;\nLIBERTY of thought, expression, belief, faith and worship;\nEQUALITY of status and of opportunity;\nand to promote among them all\nFRATERNITY assuring the dignity of the individual and the unity and integrity of the Nation;\nIN OUR CONSTITUENT ASSEMBLY this twenty-sixth day of November, 1949, do HEREBY ADOPT, ENACT AND GIVE TO OURSELVES THIS CONSTITUTION.",
    part: "Introduction",
    landmarkCases: [],
    tags: ["Preamble", "Philosophy", "Sovereign", "Secular", "Justice"],
    limitationsAndExceptions: "The Preamble is part of the Constitution but is not directly enforceable in a court of law. It is used to interpret ambiguous provisions of the Constitution.",
    fillInTheBlanks: [
      { question: "The terms 'Socialist' and 'Secular' were added to the Preamble by the ____ Constitutional Amendment.", answer: "42nd" }
    ]
  },
  // PART I: THE UNION AND ITS TERRITORY
  {
    id: "Article 1",
    title: "Name and territory of the Union",
    summary: "India, also known as Bharat, is a Union of States. Its territory comprises states, union territories, and any acquired territories, signifying an indivisible and permanent union.",
    detailedExplanation: "This foundational article establishes the identity of the nation with two official names, 'India' and 'Bharat'. It defines the country's political structure as a 'Union of States' to signify that India is an indivisible whole and that states have no right to secede. The territory of India is explicitly defined to include the territories of the States, the Union territories as specified in the First Schedule, and any other territories that may be acquired in the future.",
    fullText: "(1) India, that is Bharat, shall be a Union of States.\n(2) The States and the territories thereof shall be as specified in the First Schedule.\n(3) The territory of India shall comprise—\n(a) the territories of the States;\n(b) the Union territories specified in the First Schedule; and\n(c) such other territories as may be acquired.",
    part: "Part I: The Union and its Territory",
    landmarkCases: [],
    tags: ["Union", "Territory", "Bharat", "State Formation"],
    limitationsAndExceptions: "The term 'Union of States' signifies that states cannot secede from India. India is an indivisible and permanent Union.",
    relatedArticles: ["Article 2", "Article 3", "Article 4"],
  },
  {
    id: "Article 2",
    title: "Admission or establishment of new States",
    summary: "Gives Parliament the power to admit new territories into India or establish new states that are not part of India's existing territory.",
    detailedExplanation: "Article 2 grants Parliament the power to admit into the Union, or establish, new States that are not currently part of India. The term 'admit' refers to including an existing political entity, while 'establish' refers to creating a new state from a territory that was not previously a state. This power applies to territories lying outside the current territory of India.",
    fullText: "Parliament may by law admit into the Union, or establish, new States on such terms and conditions as it thinks fit.",
    part: "Part I: The Union and its Territory",
    landmarkCases: [],
    tags: ["Parliament", "New States", "Admission"],
    limitationsAndExceptions: "This power applies to territories outside India's existing boundaries. The terms and conditions for admission or establishment are at the complete discretion of the Parliament. Laws made under this article require only a simple majority.",
    relatedArticles: ["Article 1", "Article 3", "Article 4"],
  },
  {
    id: "Article 3",
    title: "Formation of new States and alteration of areas, boundaries or names of existing States",
    summary: "Empowers Parliament to form new states, alter areas, boundaries, or names of existing states within India. The state's opinion is not binding on Parliament.",
    detailedExplanation: "This article gives Parliament the power to reorganize the states internally by law. It can form a new state, increase or diminish the area of any state, alter its boundaries, or change its name. This power highlights the flexibility of India's federal structure. The procedure requires that a bill for this purpose can only be introduced on the recommendation of the President, who must refer the bill to the legislature of the affected state for its views. However, Parliament is not bound by these views.",
    fullText: "Parliament may by law—\n(a) form a new State by separation of territory from any State or by uniting two or more States or parts of States or by uniting any territory to a part of any State;\n(b) increase the area of any State;\n(c) diminish the area of any State;\n(d) alter the boundaries of any State;\n(e) alter the name of any State:\nProvided that no Bill for the purpose shall be introduced in either House of Parliament except on the recommendation of the President and unless, where the proposal contained in the Bill affects the area, boundaries or name of any of the States, the Bill has been referred by the President to the Legislature of that State for expressing its views thereon...",
    part: "Part I: The Union and its Territory",
    landmarkCases: [],
    tags: ["State Reorganization", "Parliament", "Boundaries"],
    limitationsAndExceptions: "A bill for such changes requires prior recommendation from the President and must be referred to the state legislature for its opinion, but this opinion is not binding on Parliament. Such laws can be passed by a simple majority.",
    relatedArticles: ["Article 1", "Article 2", "Article 4"],
  },
  {
    id: "Article 4",
    title: "Laws made under Articles 2 and 3 to provide for the amendment of the First and the Fourth Schedules",
    summary: "Clarifies that laws made under Articles 2 and 3, which alter state boundaries, are not considered constitutional amendments under Article 368 and can be passed by a simple majority.",
    detailedExplanation: "Article 4 is a consequential provision that clarifies the legislative process for laws made under Articles 2 and 3. It states that any such law will contain provisions to amend the First Schedule (listing states and UTs) and the Fourth Schedule (allocating Rajya Sabha seats) as necessary. Crucially, it declares that no such law shall be considered a constitutional amendment under Article 368. This mechanism allows for the territorial reorganization of India through a simple majority in Parliament.",
    fullText: "(1) Any law referred to in article 2 or article 3 shall contain such provisions for the amendment of the First Schedule and the Fourth Schedule as may be necessary to give effect to the provisions of the law...\n(2) No such law as aforesaid shall be deemed to be an amendment of this Constitution for the purposes of article 368.",
    part: "Part I: The Union and its Territory",
    landmarkCases: [],
    tags: ["Simple Majority", "Constitutional Amendment", "Schedules"],
    limitationsAndExceptions: "Such laws shall not be deemed a constitutional amendment under Article 368, simplifying the process of state reorganization.",
    relatedArticles: ["Article 2", "Article 3"],
  },
  // PART II: CITIZENSHIP
  {
    id: "Article 5",
    title: "Citizenship at the commencement of the Constitution",
    summary: "Defines who was a citizen of India on January 26, 1950, based on domicile and either birth in India, parent's birth in India, or residence for at least five years.",
    detailedExplanation: "This article laid down the rules for who would be considered a citizen of India when the Constitution came into force. The mandatory condition was 'domicile' in India (permanent residence). Along with domicile, one of the following three conditions had to be met: (a) the person was born in India, (b) either of their parents was born in India, or (c) they had been ordinarily residing in India for at least five years before commencement.",
    fullText: "At the commencement of this Constitution, every person who has his domicile in the territory of India and—\n(a) who was born in the territory of India; or\n(b) either of whose parents was born in the territory of India; or\n(c) who has been ordinarily resident in the territory of India for not less than five years immediately preceding such commencement, shall be a citizen of India.",
    part: "Part II: Citizenship",
    landmarkCases: [],
    tags: ["Citizenship", "Domicile"],
    limitationsAndExceptions: "These provisions were applicable only at the commencement of the Constitution. Future matters of citizenship are governed by laws made by Parliament under Article 11.",
    relatedArticles: ["Article 9", "Article 10", "Article 11"],
  },
  {
    id: "Article 6",
    title: "Rights of citizenship of certain persons who have migrated to India from Pakistan",
    summary: "Grants citizenship to people who migrated from Pakistan to India before July 19, 1948, or those who migrated after but registered as citizens.",
    detailedExplanation: "This article was created to address the mass migration during the Partition. It granted citizenship to those who moved from Pakistan to India. It set a cut-off date of July 19, 1948. Those who migrated before this date became citizens if they ordinarily resided in India. Those who migrated on or after this date had to reside in India for at least six months and then register with a government officer to become a citizen.",
    fullText: "Notwithstanding anything in article 5, a person who has migrated to the territory of India from the territory now included in Pakistan shall be deemed to be a citizen of India at the commencement of this Constitution if he or either of his parents or any of his grand-parents was born in India...",
    part: "Part II: Citizenship",
    landmarkCases: [],
    tags: ["Citizenship", "Partition", "Migration"],
    limitationsAndExceptions: "This provision is specific to the historical context of Partition and is not applicable to modern migration.",
    relatedArticles: ["Article 5", "Article 7"],
  },
  {
    id: "Article 7",
    title: "Rights of citizenship of certain migrants to Pakistan",
    summary: "Strips Indian citizenship from those who migrated to Pakistan after March 1, 1947, but allows them to regain it if they return to India under a permit for resettlement.",
    detailedExplanation: "This article deals with individuals who migrated from India to Pakistan after March 1, 1947. It states that such persons shall not be considered citizens of India. However, it provides an exception for those who returned to India with a permit for resettlement or permanent return. Such persons could acquire citizenship through registration.",
    fullText: "Notwithstanding anything in articles 5 and 6, a person who has after the first day of March, 1947, migrated from the territory of India to the territory now included in Pakistan shall not be deemed to be a citizen of India...",
    part: "Part II: Citizenship",
    landmarkCases: [],
    tags: ["Citizenship", "Partition", "Migration"],
    limitationsAndExceptions: "This article overrides Articles 5 and 6 and has a specific historical context tied to Partition.",
    relatedArticles: ["Article 5", "Article 6"],
  },
  {
    id: "Article 8",
    title: "Rights of citizenship of certain persons of Indian origin residing outside India",
    summary: "Grants Indian citizenship to persons of Indian origin (PIO) residing outside undivided India, if they register as a citizen with an Indian diplomatic mission.",
    detailedExplanation: "This article extends a path to citizenship for the Indian diaspora. It allows a person of Indian origin residing outside undivided India to become a citizen if they, or their parents or grandparents, were born in India (as defined in the 1935 Act). To acquire citizenship, the person must formally apply and be registered by an Indian diplomatic or consular representative.",
    fullText: "Notwithstanding anything in article 5, any person who or either of whose parents or any of whose grand-parents was born in India... and who is ordinarily residing in any country outside India... shall be deemed to be a citizen of India if he has been registered as a citizen of India...",
    part: "Part II: Citizenship",
    landmarkCases: [],
    tags: ["Citizenship", "PIO", "Diaspora"],
    limitationsAndExceptions: "This is not an automatic grant of citizenship; it requires formal application and registration.",
    relatedArticles: ["Article 5"],
  },
  {
    id: "Article 9",
    title: "Persons voluntarily acquiring citizenship of a foreign State not to be citizens",
    summary: "A person who voluntarily acquires the citizenship of a foreign country shall no longer be a citizen of India, reinforcing the principle of single citizenship.",
    detailedExplanation: "This article firmly establishes the principle of single citizenship in India. It explicitly states that any person who voluntarily acquires the citizenship of another country automatically loses their Indian citizenship. This provision applies to those who would otherwise be citizens under Articles 5, 6, or 8. It ensures that there is no dual citizenship.",
    fullText: "No person shall be a citizen of India by virtue of article 5, or be deemed to be a citizen of India by virtue of article 6 or article 8, if he has voluntarily acquired the citizenship of any foreign State.",
    part: "Part II: Citizenship",
    landmarkCases: [],
    tags: ["Citizenship", "Dual Citizenship", "Termination"],
    limitationsAndExceptions: "The loss of Indian citizenship is automatic upon voluntarily acquiring foreign citizenship. The article enforces the principle of single citizenship without exception.",
    relatedArticles: ["Article 5", "Article 10", "Article 11"],
  },
  {
    id: "Article 10",
    title: "Continuance of the rights of citizenship",
    summary: "Every person who is a citizen of India under any of the foregoing provisions shall continue to be a citizen, subject to any law made by Parliament.",
    detailedExplanation: "This article ensures the continuity of citizenship for those who became citizens at the commencement of the Constitution. However, this right is not absolute and is explicitly made subject to any laws that Parliament might enact, linking the constitutional grant of citizenship to Parliament's future legislative power.",
    fullText: "Every person who is or is deemed to be a citizen of India under any of the foregoing provisions of this Part shall, subject to the provisions of any law that may be made by Parliament, continue to be such citizen.",
    part: "Part II: Citizenship",
    landmarkCases: [],
    tags: ["Citizenship", "Parliament"],
    limitationsAndExceptions: "The right to continue as a citizen is not absolute and is subject to laws made by Parliament.",
    relatedArticles: ["Article 5", "Article 11"],
  },
  {
    id: "Article 11",
    title: "Parliament to regulate the right of citizenship by law",
    summary: "Gives Parliament the exclusive power to make any provision with respect to the acquisition and termination of citizenship and all other matters relating to it.",
    detailedExplanation: "This article grants Parliament exclusive and complete authority over all aspects of citizenship after the Constitution's commencement. Using this power, Parliament enacted the Citizenship Act, 1955, which specifies various modes of acquiring and terminating citizenship.",
    fullText: "Nothing in the foregoing provisions of this Part shall derogate from the power of Parliament to make any provision with respect to the acquisition and termination of citizenship and all other matters relating to citizenship.",
    part: "Part II: Citizenship",
    landmarkCases: [],
    tags: ["Citizenship", "Parliament", "Citizenship Act"],
    limitationsAndExceptions: "This article grants plenary power to Parliament over citizenship laws, which must be consistent with other constitutional provisions.",
    relatedArticles: ["Article 5", "Article 9", "Article 10"],
  },
  {
    id: "Article 12",
    title: "Definition of 'the State'",
    summary: "Defines 'the State' to include the Government and Parliament of India, state governments and legislatures, and all local or other authorities within India or under the control of the Government of India.",
    detailedExplanation: "This article is crucial as Fundamental Rights are primarily enforceable against 'the State'. Article 12 provides a broad definition to include all levels of government and 'other authorities' under government control, such as bodies receiving funding or performing public interest functions.",
    fullText: "In this Part, unless the context otherwise requires, 'the State' includes the Government and Parliament of India and the Government and the Legislature of each of the States and all local or other authorities within the territory of India or under the control of the Government of India.",
    part: "Part III: Fundamental Rights",
    landmarkCases: [],
    tags: ["Fundamental Rights", "State", "Definition"],
    limitationsAndExceptions: "The definition primarily covers governmental and quasi-governmental bodies. Actions of purely private individuals are generally outside its scope, except for certain rights like Article 17.",
    relatedArticles: ["Article 13", "Article 32", "Article 36"],
  },
  {
    id: "Article 13",
    title: "Laws inconsistent with or in derogation of the fundamental rights",
    summary: "Declares that any law which is inconsistent with or takes away any of the fundamental rights shall be void. This establishes the power of judicial review.",
    detailedExplanation: "Article 13 is the 'protective shield' of Fundamental Rights and the foundation of judicial review. Clause (1) voids pre-constitutional laws inconsistent with FRs. Clause (2) prohibits the State from making new laws that abridge FRs. Clause (3)(a) defines 'Law' broadly to include ordinances, orders, rules, customs, etc. The 'Basic Structure Doctrine' from Kesavananda Bharati (1973) ensures that even constitutional amendments cannot alter the fundamental framework of the Constitution.",
    fullText: "(1) All laws in force in the territory of India immediately before the commencement of this Constitution, in so far as they are inconsistent with the provisions of this Part, shall, to the extent of such inconsistency, be void.\n(2) The State shall not make any law which takes away or abridges the rights conferred by this Part and any law made in contravention of this clause shall, to the extent of the contravention, be void...",
    part: "Part III: Fundamental Rights",
    landmarkCases: [
      { caseName: "Kesavananda Bharati v. State of Kerala (1973)", caseSummary: "The Supreme Court introduced the 'Basic Structure Doctrine,' ruling that Parliament cannot amend the Constitution in a way that alters its fundamental framework." }
    ],
    tags: ["Fundamental Rights", "Judicial Review", "Basic Structure"],
    limitationsAndExceptions: "The 'Basic Structure Doctrine' acts as a check on Parliament's power to amend the constitution, even though amendments are not explicitly 'laws' under this article.",
    relatedArticles: ["Article 12", "Article 32", "Article 368"],
  },
  {
    id: "Article 14",
    title: "Equality before law",
    summary: "The State shall not deny to any person equality before the law or the equal protection of the laws within the territory of India.",
    detailedExplanation: "Article 14 guarantees the right to equality to every person, citizen or foreigner. It has two aspects: 'Equality before the law,' a British concept, means no person is above the law. 'Equal protection of the laws,' an American concept, means that law should be applied equally to all persons who are similarly situated. It permits 'reasonable classification' but prohibits arbitrary action.",
    fullText: "The State shall not deny to any person equality before the law or the equal protection of the laws within the territory of India.",
    part: "Part III: Fundamental Rights",
    landmarkCases: [],
    tags: ["Fundamental Rights", "Equality"],
    limitationsAndExceptions: "The right is not absolute and allows for 'reasonable classification' based on intelligible differentia with a rational nexus to the law's objective.",
    relatedArticles: ["Article 15", "Article 16"],
    fillInTheBlanks: [{ question: "The State shall not deny to any person equality before the law or the ____ protection of the laws.", answer: "equal" }]
  },
   {
    id: "Article 15",
    title: "Prohibition of discrimination on grounds of religion, race, caste, sex or place of birth",
    summary: "Prohibits the State from discriminating against any citizen on grounds only of religion, race, caste, sex, or place of birth. It also allows for special provisions for women, children, and backward classes.",
    detailedExplanation: "Article 15 specifically prohibits discrimination on five grounds, exclusively for Indian citizens. It also contains exceptions for affirmative action: Clause (3) for women and children, Clause (4) (added by 1st Amendment, 1951) for socially and educationally backward classes (SEBCs), and Clause (6) (added by 103rd Amendment, 2019) for Economically Weaker Sections (EWS).",
    fullText: "(1) The State shall not discriminate against any citizen on grounds only of religion, race, caste, sex, place of birth or any of them.\n(2) No citizen shall, on grounds only of religion, race, caste, sex, place of birth or any of them, be subject to any disability, liability, restriction or condition...",
    part: "Part III: Fundamental Rights",
    landmarkCases: [],
    tags: ["Fundamental Rights", "Equality", "Discrimination", "Reservation"],
    limitationsAndExceptions: "The prohibition on discrimination is on the specified grounds 'only'. The article itself contains positive exceptions to allow the state to make special provisions (affirmative action) for specific groups.",
    relatedArticles: ["Article 14", "Article 16"],
  },
  {
    id: "Article 16",
    title: "Equality of opportunity in matters of public employment",
    summary: "Guarantees equality of opportunity for all citizens in public employment and prohibits discrimination on seven grounds, including descent and residence.",
    detailedExplanation: "This article ensures a level playing field for all citizens in government jobs. It prohibits discrimination on seven grounds (religion, race, caste, sex, descent, place of birth, or residence). It contains exceptions for affirmative action, such as Clause (4) for backward classes and Clause (6) (added by 103rd Amendment, 2019) for 10% EWS reservation.",
    fullText: "(1) There shall be equality of opportunity for all citizens in matters relating to employment or appointment to any office under the State.\n(2) No citizen shall, on grounds only of religion, race, caste, sex, descent, place of birth, residence or any of them, be ineligible for, or discriminated against...",
    part: "Part III: Fundamental Rights",
    landmarkCases: [],
    tags: ["Fundamental Rights", "Equality", "Public Employment", "Reservation"],
    limitationsAndExceptions: "This article allows for reservations in public employment for backward classes, SCs, STs, and EWS.",
    relatedArticles: ["Article 14", "Article 15"],
  },
  {
    id: "Article 17",
    title: "Abolition of Untouchability",
    summary: "'Untouchability' is abolished and its practice in any form is forbidden. Enforcing any disability arising from 'Untouchability' is a punishable offence.",
    detailedExplanation: "This is a powerful and absolute provision aimed at eradicating the social evil of untouchability. It is one of the few fundamental rights enforceable against both the state and private individuals. The practice is a punishable offence.",
    fullText: "'Untouchability' is abolished and its practice in any form is forbidden. The enforcement of any disability arising out of 'Untouchability' shall be an offence punishable in accordance with law.",
    part: "Part III: Fundamental Rights",
    landmarkCases: [],
    tags: ["Fundamental Rights", "Equality", "Untouchability", "Discrimination"],
    limitationsAndExceptions: "This right is absolute and has no constitutional limitations.",
    relatedArticles: ["Article 14", "Article 15"],
    fillInTheBlanks: [{ question: "'____' is abolished and its practice in any form is forbidden.", answer: "Untouchability" }]
  },
  {
    id: "Article 18",
    title: "Abolition of titles",
    summary: "Prohibits the State from conferring titles, except for military and academic distinctions. Citizens are also prohibited from accepting any title from a foreign state.",
    detailedExplanation: "This article aims to establish social equality by abolishing hereditary titles of nobility. The state is barred from conferring any titles except military (e.g., General) and academic (e.g., Dr.) distinctions, which are based on merit. Citizens cannot accept foreign titles.",
    fullText: "(1) No title, not being a military or academic distinction, shall be conferred by the State.\n(2) No citizen of India shall accept any title from any foreign State...",
    part: "Part III: Fundamental Rights",
    landmarkCases: [],
    tags: ["Fundamental Rights", "Equality", "Titles"],
    limitationsAndExceptions: "The article explicitly exempts military and academic distinctions.",
    relatedArticles: ["Article 14"],
  },
  {
    id: "Article 19",
    title: "Protection of certain rights regarding freedom of speech, etc.",
    summary: "Guarantees six fundamental freedoms to citizens: speech and expression, assembly, association, movement, residence, and profession, subject to reasonable restrictions.",
    detailedExplanation: "Article 19(1) guarantees six essential freedoms for citizens, including speech and expression (19(1)(a)). These freedoms are not absolute and are subject to 'reasonable restrictions' by the state on grounds specified in clauses (2) to (6), such as sovereignty and integrity of India, public order, decency, or morality.",
    fullText: "(1) All citizens shall have the right—\n(a) to freedom of speech and expression;\n(b) to assemble peaceably and without arms;\n(c) to form associations or unions or co-operative societies;\n(d) to move freely throughout the territory of India;\n(e) to reside and settle in any part of the territory of India; and\n(g) to practise any profession, or to carry on any occupation, trade or business...",
    part: "Part III: Fundamental Rights",
    landmarkCases: [],
    tags: ["Fundamental Rights", "Freedom of Speech", "Liberty"],
    limitationsAndExceptions: "All freedoms are subject to 'reasonable restrictions' by the State on specific grounds mentioned in clauses (2) to (6) of Article 19.",
    relatedArticles: ["Article 21"],
  },
  {
    id: "Article 20",
    title: "Protection in respect of conviction for offences",
    summary: "Provides three safeguards for accused persons: protection against ex-post-facto law, double jeopardy, and self-incrimination. Cannot be suspended during an Emergency.",
    detailedExplanation: "This article provides three crucial protections to any person accused of a crime: (1) No ex-post-facto law (Clause 1): A person cannot be convicted for an act that was not an offence when committed. (2) No double jeopardy: A person cannot be prosecuted and punished for the same offence more than once. (3) No self-incrimination (Clause 3): An accused person cannot be compelled to be a witness against themselves. These remain in force even during an emergency.",
    fullText: "(1) No person shall be convicted of any offence except for violation of a law in force at the time of the commission of the Act charged as an offence...\n(2) No person shall be prosecuted and punished for the same offence more than once.\n(3) No person accused of any offence shall be compelled to be a witness against himself.",
    part: "Part III: Fundamental Rights",
    landmarkCases: [],
    tags: ["Fundamental Rights", "Criminal Justice", "Liberty"],
    limitationsAndExceptions: "Protection against double jeopardy applies only to punishment by a court, not departmental proceedings. Protection against self-incrimination does not extend to giving physical evidence like fingerprints.",
    relatedArticles: ["Article 21", "Article 22"],
  },
  {
    id: "Article 21",
    title: "Protection of life and personal liberty",
    summary: "No person shall be deprived of their life or personal liberty except according to procedure established by law. This right is available to all and cannot be suspended during an emergency.",
    detailedExplanation: "Article 21 is a cornerstone of fundamental rights, with a very wide scope. The Supreme Court has interpreted 'life' to mean the right to live with human dignity. The 'procedure established by law' must be fair, just, and reasonable. Numerous rights have been read into Article 21, including the right to privacy, a clean environment, and a speedy trial. Protection under this right remains active even during an Emergency (as ensured by the 44th Amendment, 1978).",
    fullText: "No person shall be deprived of his life or personal liberty except according to procedure established by law.",
    part: "Part III: Fundamental Rights",
    landmarkCases: [
      { caseName: "Maneka Gandhi v. Union of India (1978)", caseSummary: "The Supreme Court held that the 'procedure established by law' under Article 21 must be fair, just, and reasonable." },
      { caseName: "Justice K.S. Puttaswamy (Retd.) v. Union of India (2017)", caseSummary: "A nine-judge bench unanimously affirmed that the Right to Privacy is a fundamental right under Article 21." }
    ],
    tags: ["Fundamental Rights", "Life and Liberty", "Privacy"],
    limitationsAndExceptions: "This right can be curtailed only 'according to procedure established by law,' which must be fair. This right cannot be suspended even during a national emergency.",
    relatedArticles: ["Article 14", "Article 19", "Article 20", "Article 21A"],
  },
  {
    id: "Article 21A",
    title: "Right to education",
    summary: "The State shall provide free and compulsory education to all children of the age of six to fourteen years.",
    detailedExplanation: "Inserted by the 86th Constitutional Amendment in 2002, this article elevated the right to education to a fundamental right. It places a positive obligation on the state to provide free and compulsory elementary education to all children between 6 and 14 years old.",
    fullText: "The State shall provide free and compulsory education to all children of the age of six to fourteen years in such manner as the State may, by law, determine.",
    part: "Part III: Fundamental Rights",
    landmarkCases: [],
    tags: ["Fundamental Rights", "Education"],
    limitationsAndExceptions: "The right is specific to the age group of 6 to 14 years. It does not cover early childhood care (below 6 years) or higher education.",
    relatedArticles: ["Article 21", "Article 45", "Article 51A"],
    fillInTheBlanks: [{ question: "The State shall provide free and compulsory education to all children of the age of ____ to fourteen years.", answer: "six" }]
  },
  {
    id: "Article 22",
    title: "Protection against arrest and detention in certain cases",
    summary: "Provides procedural safeguards against arbitrary arrest and detention, including the right to be informed of grounds of arrest, consult a lawyer, and be produced before a magistrate within 24 hours.",
    detailedExplanation: "This article provides safeguards against two types of detention: punitive (after a crime) and preventive (on suspicion). For punitive detention, it guarantees the right to be informed of the grounds of arrest, the right to a lawyer, and the right to be produced before a magistrate within 24 hours. These rights are not available to enemy aliens or those under preventive detention.",
    fullText: "(1) No person who is arrested shall be detained in custody without being informed, as soon as may be, of the grounds for such arrest nor shall he be denied the right to consult, and to be defended by, a legal practitioner of his choice.\n(2) Every person who is arrested and detained in custody shall be produced before the nearest magistrate within a period of twenty-four hours...",
    part: "Part III: Fundamental Rights",
    landmarkCases: [],
    tags: ["Fundamental Rights", "Arrest and Detention", "Liberty"],
    limitationsAndExceptions: "The safeguards in clauses (1) and (2) are not available to enemy aliens or persons arrested under a preventive detention law.",
    relatedArticles: ["Article 20", "Article 21"],
  },
  {
    id: "Article 23",
    title: "Prohibition of traffic in human beings and forced labour",
    summary: "Prohibits human trafficking, 'begar' (forced labour without payment), and other similar forms of forced labour. Any contravention is a punishable offence.",
    detailedExplanation: "This article provides protection against exploitation. It prohibits traffic in human beings, bonded labour, and other forms of forced work without payment (begar). Any violation is a punishable offense. The State can impose compulsory public service (e.g., military duty) without violating this article, provided there is no discrimination.",
    fullText: "(1) Traffic in human beings and begar and other similar forms of forced labour are prohibited and any contravention of this provision shall be an offence punishable in accordance with law.\n(2) Nothing in this article shall prevent the State from imposing compulsory service for public purposes...",
    part: "Part III: Fundamental Rights",
    landmarkCases: [],
    tags: ["Fundamental Rights", "Exploitation", "Forced Labour"],
    limitationsAndExceptions: "The article provides an exception for the State to impose compulsory service for public purposes, provided it does not discriminate.",
    relatedArticles: ["Article 24", "Article 35"],
  },
  {
    id: "Article 24",
    title: "Prohibition of employment of children in factories, etc.",
    summary: "Prohibits the employment of children below the age of fourteen years in any factory, mine, or other hazardous employment.",
    detailedExplanation: "This article provides for the protection of children from exploitation by prohibiting their employment in hazardous occupations. This is an absolute prohibition for children under 14 years.",
    fullText: "No child below the age of fourteen years shall be employed to work in any factory or mine or engaged in any other hazardous employment.",
    part: "Part III: Fundamental Rights",
    landmarkCases: [],
    tags: ["Fundamental Rights", "Exploitation", "Child Labour"],
    limitationsAndExceptions: "The prohibition is absolute for hazardous employment for children under 14.",
    relatedArticles: ["Article 21A", "Article 23", "Article 45"],
  },
  {
    id: "Article 25",
    title: "Freedom of conscience and free profession, practice and propagation of religion",
    summary: "Guarantees all persons the freedom of conscience and the right to freely profess, practice, and propagate religion, subject to public order, morality, and health.",
    detailedExplanation: "This article guarantees individual religious freedom. It includes freedom of conscience, the right to profess, practice, and propagate religion. This freedom is not absolute and is subject to public order, morality, health, and other fundamental rights.",
    fullText: "(1) Subject to public order, morality and health and to the other provisions of this Part, all persons are equally entitled to freedom of conscience and the right freely to profess, practise and propagate religion.",
    part: "Part III: Fundamental Rights",
    landmarkCases: [],
    tags: ["Fundamental Rights", "Religion", "Secularism"],
    limitationsAndExceptions: "This right is subject to public order, morality, health, and other Fundamental Rights.",
    relatedArticles: ["Article 26", "Article 27", "Article 28"],
  },
  {
    id: "Article 26",
    title: "Freedom to manage religious affairs",
    summary: "Gives every religious denomination the right to establish and maintain religious institutions, manage its own religious affairs, and own and administer property.",
    detailedExplanation: "While Article 25 protects individual religious freedom, Article 26 protects the collective freedom of religious denominations. It grants them the right to establish and maintain institutions, manage their own religious affairs, and own property, subject to public order, morality, and health.",
    fullText: "Subject to public order, morality and health, every religious denomination or any section thereof shall have the right—\n(a) to establish and maintain institutions for religious and charitable purposes;\n(b) to manage its own affairs in matters of religion...",
    part: "Part III: Fundamental Rights",
    landmarkCases: [],
    tags: ["Fundamental Rights", "Religion", "Secularism"],
    limitationsAndExceptions: "This right is also subject to public order, morality, and health. The state can regulate secular administrative activities.",
    relatedArticles: ["Article 25"],
  },
  {
    id: "Article 27",
    title: "Freedom as to payment of taxes for promotion of any particular religion",
    summary: "No person shall be compelled to pay any taxes for the promotion or maintenance of any particular religion.",
    detailedExplanation: "This article reinforces India's secular character by prohibiting the state from levying a tax and using public funds to promote any specific religion. It ensures that public money is not used to favor one religion over another.",
    fullText: "No person shall be compelled to pay any taxes, the proceeds of which are specifically appropriated in payment of expenses for the promotion or maintenance of any particular religion or religious denomination.",
    part: "Part III: Fundamental Rights",
    landmarkCases: [],
    tags: ["Fundamental Rights", "Religion", "Secularism", "Taxation"],
    limitationsAndExceptions: "The article prohibits a 'tax' but not a 'fee' for secular services provided by the state.",
    relatedArticles: ["Article 25"],
  },
  {
    id: "Article 28",
    title: "Freedom as to attendance at religious instruction or religious worship in certain educational institutions",
    summary: "Prohibits religious instruction in state-run educational institutions. In other institutions, attendance is not compulsory without consent.",
    detailedExplanation: "Clause (1) absolutely prohibits religious instruction in institutions wholly maintained out of State funds. In state-recognized or state-aided institutions, no student can be compelled to attend religious instruction without their consent.",
    fullText: "(1) No religious instruction shall be provided in any educational institution wholly maintained out of State funds.\n(3) No person attending any educational institution recognised by the State or receiving aid...shall be required to take part in any religious instruction...",
    part: "Part III: Fundamental Rights",
    landmarkCases: [],
    tags: ["Fundamental Rights", "Religion", "Education", "Secularism"],
    limitationsAndExceptions: "The absolute prohibition applies only to institutions 'wholly maintained out of State funds'.",
    relatedArticles: ["Article 25", "Article 29", "Article 30"],
  },
  {
    id: "Article 29",
    title: "Protection of interests of minorities",
    summary: "Guarantees the right of any section of citizens to conserve their distinct language, script, or culture, and prohibits denial of admission to state-funded educational institutions on grounds of religion, race, caste, or language.",
    detailedExplanation: "This article provides cultural and educational rights. Clause (1) gives any section of citizens (not just minorities) the right to conserve their distinct language, script, or culture. Clause (2) prohibits denial of admission to state-maintained or aided institutions based only on religion, race, caste, or language.",
    fullText: "(1) Any section of the citizens residing in the territory of India or any part thereof having a distinct language, script or culture of its own shall have the right to conserve the same.\n(2) No citizen shall be denied admission into any educational institution maintained by the State or receiving aid... on grounds only of religion, race, caste, language or any of them.",
    part: "Part III: Fundamental Rights",
    landmarkCases: [],
    tags: ["Fundamental Rights", "Minority Rights", "Education", "Culture"],
    limitationsAndExceptions: "The right in Clause (1) is available to any section of citizens, majority or minority.",
    relatedArticles: ["Article 15", "Article 30"],
  },
  {
    id: "Article 30",
    title: "Right of minorities to establish and administer educational institutions",
    summary: "All religious or linguistic minorities have the right to establish and administer educational institutions of their choice. The State shall not discriminate in granting aid.",
    detailedExplanation: "This article provides a crucial right to religious and linguistic minorities to establish their own educational institutions to preserve their culture and language. The state is also barred from discriminating against these institutions when providing financial aid.",
    fullText: "(1) All minorities, whether based on religion or language, shall have the right to establish and administer educational institutions of their choice.\n(2) The State shall not, in granting aid...discriminate against any educational institution on the ground that it is under the management of a minority...",
    part: "Part III: Fundamental Rights",
    landmarkCases: [],
    tags: ["Fundamental Rights", "Minority Rights", "Education"],
    limitationsAndExceptions: "The right to administer does not mean the right to maladminister. The State can impose reasonable regulations for academic standards.",
    relatedArticles: ["Article 29"],
  },
  {
    id: "Article 32",
    title: "Remedies for enforcement of rights conferred by this Part",
    summary: "Guarantees the right to move the Supreme Court for the enforcement of Fundamental Rights. Dr. B.R. Ambedkar called it the 'heart and soul' of the Constitution.",
    detailedExplanation: "Dr. B.R. Ambedkar called this article the 'heart and soul' of the Constitution. It guarantees an effective remedy for the violation of other fundamental rights. It designates the Supreme Court as the protector of these rights, empowering it to issue five types of writs: Habeas Corpus, Mandamus, Prohibition, Certiorari, and Quo Warranto.",
    fullText: "(1) The right to move the Supreme Court by appropriate proceedings for the enforcement of the rights conferred by this Part is guaranteed.\n(2) The Supreme Court shall have power to issue directions or orders or writs...",
    part: "Part III: Fundamental Rights",
    landmarkCases: [],
    tags: ["Fundamental Rights", "Judicial Review", "Writs", "Supreme Court"],
    limitationsAndExceptions: "This right can be suspended during a National Emergency (except for violations of Articles 20 and 21).",
    relatedArticles: ["Article 13", "Article 226"],
    fillInTheBlanks: [{ question: "The Supreme Court shall have power to issue directions or orders or ____...", answer: "writs" }]
  },
  {
    id: "Article 33",
    title: "Power of Parliament to modify the rights conferred by this Part in their application to Forces, etc.",
    summary: "Allows Parliament to restrict or abrogate the fundamental rights of members of the Armed Forces, paramilitary forces, police, and intelligence agencies to ensure discipline.",
    detailedExplanation: "This article grants Parliament the power to make laws that limit the fundamental rights of personnel in specific crucial services like the armed forces and intelligence agencies to ensure discipline and duty, which are vital for national security.",
    fullText: "Parliament may, by law, determine to what extent any of the rights conferred by this Part shall, in their application to,—\n(a) the members of the Armed Forces; or\n(b) the members of the Forces charged with the maintenance of public order...",
    part: "Part III: Fundamental Rights",
    landmarkCases: [],
    tags: ["Fundamental Rights", "Parliament", "Armed Forces"],
    limitationsAndExceptions: "The power to make such restrictive laws is vested exclusively with the Parliament, not state legislatures.",
    relatedArticles: ["Article 34"],
  },
  {
    id: "Article 34",
    title: "Restriction on rights conferred by this Part while martial law is in force in any area",
    summary: "Restricts fundamental rights while martial law is in force and empowers Parliament to indemnify any government servant for acts done to maintain order.",
    detailedExplanation: "This article provides for the restriction of fundamental rights when martial law is in force. It empowers Parliament to pass an 'Act of Indemnity' to legally protect officials from legal action for acts committed while maintaining order under martial law.",
    fullText: "Parliament may by law indemnify any person in the service of the Union or of a State... in respect of any act done by him in connection with the maintenance or restoration of order in any area within the territory of India where martial law was in force...",
    part: "Part III: Fundamental Rights",
    landmarkCases: [],
    tags: ["Fundamental Rights", "Parliament", "Martial Law"],
    limitationsAndExceptions: "This is an explicit exception to Fundamental Rights, applicable only in areas where martial law is in force.",
    relatedArticles: ["Article 33"],
  },
  {
    id: "Article 35",
    title: "Legislation to give effect to the provisions of this Part",
    summary: "Gives Parliament, not state legislatures, the exclusive power to make laws for prescribing punishment for offences related to certain fundamental rights.",
    detailedExplanation: "This article ensures uniformity in legislation across India regarding certain fundamental rights. It grants Parliament exclusive power to make laws prescribing punishments for acts declared as offences under Part III, such as untouchability (Article 17) and forced labour (Article 23).",
    fullText: "Parliament shall have, and the Legislature of a State shall not have, power to make laws... for prescribing punishment for those acts which are declared to be offences under this Part...",
    part: "Part III: Fundamental Rights",
    landmarkCases: [],
    tags: ["Fundamental Rights", "Parliament"],
    limitationsAndExceptions: "This article limits the legislative power of State Legislatures on certain matters of fundamental rights to ensure national uniformity.",
    relatedArticles: ["Article 17", "Article 23"],
  },
  {
    id: "Article 36",
    title: "Definition",
    summary: "Defines 'the State' for Part IV (Directive Principles) as having the same meaning as in Part III (Fundamental Rights).",
    detailedExplanation: "This article states that for the purpose of the Directive Principles of State Policy (DPSP), the term 'State' has the same meaning as defined in Article 12. This ensures that the responsibility to implement these guiding principles covers all levels of government.",
    fullText: "In this Part, unless the context otherwise requires, 'the State' has the same meaning as in Part III.",
    part: "Part IV: Directive Principles of State Policy",
    landmarkCases: [],
    tags: ["DPSP", "State", "Definition"],
    limitationsAndExceptions: "This is a definitional article. The main limitation of all DPSPs is their non-justiciable nature.",
    relatedArticles: ["Article 12", "Article 37"],
  },
  {
    id: "Article 37",
    title: "Application of the principles contained in this part",
    summary: "The Directive Principles are not enforceable by any court, but are fundamental in the governance of the country, and it is the duty of the State to apply them in making laws.",
    detailedExplanation: "This article clarifies the nature of Directive Principles. They are not justiciable, meaning citizens cannot go to court to compel the government to implement them. However, they are declared 'fundamental in the governance of the country' and impose a moral 'duty' on the State to apply them when making laws.",
    fullText: "The provisions contained in this Part shall not be enforceable by any court, but the principles therein laid down are nevertheless fundamental in the governance of the country and it shall be the duty of the State to apply these principles in making laws.",
    part: "Part IV: Directive Principles of State Policy",
    landmarkCases: [],
    tags: ["DPSP", "Governance", "Justiciability"],
    limitationsAndExceptions: "This article explicitly states that DPSPs are 'not enforceable by any court.'",
    relatedArticles: ["Article 36"],
  },
  {
    id: "Article 38",
    title: "State to secure a social order for the promotion of welfare of the people",
    summary: "The State shall strive to promote the welfare of the people by securing a social order based on social, economic, and political justice, and shall minimise inequalities.",
    detailedExplanation: "This article embodies the vision of a welfare state. It directs the state to build a social order where justice—social, economic, and political—is central. Clause (2), added by the 44th Amendment, further directs the state to reduce inequalities in income, status, and opportunities.",
    fullText: "(1) The State shall strive to promote the welfare of the people by securing and protecting as effectively as it may a social order in which justice, social, economic and political, shall inform all the institutions of the national life.\n(2) The State shall, in particular, strive to minimise the inequalities in income...",
    part: "Part IV: Directive Principles of State Policy",
    landmarkCases: [],
    tags: ["DPSP", "Welfare State", "Social Justice", "Equality"],
    limitationsAndExceptions: "As a DPSP, this is a non-justiciable directive that sets aspirational goals for the State.",
    relatedArticles: ["Article 14", "Article 39"],
  },
  {
    id: "Article 39",
    title: "Certain principles of policy to be followed by the State",
    summary: "Outlines principles for the State, including adequate means of livelihood, equitable distribution of resources, preventing concentration of wealth, and equal pay for equal work.",
    detailedExplanation: "This article lists key socio-economic goals: adequate livelihood, equitable distribution of resources, preventing concentration of wealth, equal pay for equal work, and protecting the health of workers and children.",
    fullText: "The State shall, in particular, direct its policy towards securing—\n(a) that the citizens, men and women equally, have the right to an adequate means of livelihood;\n(b) that the ownership and control of the material resources of the community are so distributed as best to subserve the common good...",
    part: "Part IV: Directive Principles of State Policy",
    landmarkCases: [],
    tags: ["DPSP", "Social Justice", "Economic Justice", "Equality"],
    limitationsAndExceptions: "These are non-justiciable principles, though courts have sometimes linked them to Fundamental Rights.",
    relatedArticles: ["Article 14", "Article 38"],
  },
  {
    id: "Article 39A",
    title: "Equal justice and free legal aid",
    summary: "The State shall provide free legal aid to ensure that justice is not denied to any citizen due to economic or other disabilities.",
    detailedExplanation: "Added by the 42nd Amendment, this DPSP directs the state to provide free legal aid to the poor and weaker sections so that justice is not denied due to economic hardship. This led to the enactment of the Legal Services Authorities Act, 1987.",
    fullText: "The State shall secure that the operation of the legal system promotes justice, on a basis of equal opportunity, and shall, in particular, provide free legal aid... to ensure that opportunities for securing justice are not denied...",
    part: "Part IV: Directive Principles of State Policy",
    landmarkCases: [],
    tags: ["DPSP", "Social Justice", "Legal Aid"],
    limitationsAndExceptions: "While this is a DPSP, the Supreme Court has made the right to free legal aid a fundamental right in criminal proceedings by linking it to Article 21.",
    relatedArticles: ["Article 14", "Article 21"],
  },
  {
    id: "Article 40",
    title: "Organisation of village panchayats",
    summary: "The State shall take steps to organise village panchayats and empower them to function as units of self-government.",
    detailedExplanation: "This is a Gandhian principle for democratic decentralization. It directs the state to establish village panchayats. This was given practical effect by the 73rd Constitutional Amendment Act of 1992, which granted constitutional status to Panchayati Raj Institutions (PRIs).",
    fullText: "The State shall take steps to organise village panchayats and endow them with such powers and authority as may be necessary to enable them to function as units of self-government.",
    part: "Part IV: Directive Principles of State Policy",
    landmarkCases: [],
    tags: ["DPSP", "Panchayats", "Gandhian Principles", "Governance"],
    limitationsAndExceptions: "This directive was non-enforceable until the 73rd Amendment made Panchayats a constitutional mandate.",
    relatedArticles: [],
  },
  {
    id: "Article 41",
    title: "Right to work, to education and to public assistance in certain cases",
    summary: "Within its economic capacity, the State shall provide for the right to work, education, and public assistance in cases of unemployment, old age, sickness, and disablement.",
    detailedExplanation: "This article directs the state to create a social safety net, but makes the right to work, education, and public assistance subject to the 'economic capacity and development' of the state. It is a goal to be achieved progressively.",
    fullText: "The State shall, within the limits of its economic capacity and development, make effective provision for securing the right to work, to education and to public assistance in cases of unemployment, old age, sickness and disablement...",
    part: "Part IV: Directive Principles of State Policy",
    landmarkCases: [],
    tags: ["DPSP", "Welfare State", "Social Security"],
    limitationsAndExceptions: "Implementation is explicitly limited by the 'economic capacity and development' of the State.",
    relatedArticles: ["Article 42", "Article 43"],
  },
  {
    id: "Article 42",
    title: "Provision for just and humane conditions of work and maternity relief",
    summary: "The State shall make provision for securing just and humane conditions of work and for maternity relief.",
    detailedExplanation: "This directive focuses on labour welfare, mandating the state to ensure safe, fair, and humane working conditions, with a specific highlight on maternity relief for working women.",
    fullText: "The State shall make provision for securing just and humane conditions of work and for maternity relief.",
    part: "Part IV: Directive Principles of State Policy",
    landmarkCases: [],
    tags: ["DPSP", "Labour Rights", "Welfare State", "Maternity"],
    limitationsAndExceptions: "This is a non-justiciable directive whose implementation depends on legislation.",
    relatedArticles: ["Article 41", "Article 43"],
  },
  {
    id: "Article 43",
    title: "Living wage, etc., for workers",
    summary: "The State shall endeavour to secure a living wage, a decent standard of life, and promote cottage industries.",
    detailedExplanation: "This article directs the state to strive for a 'living wage'—more than a minimum wage—sufficient for a decent standard of life. As a Gandhian principle, it also directs the state to promote cottage industries in rural areas.",
    fullText: "The State shall endeavour to secure, by suitable legislation or economic organisation or in any other way, to all workers... a living wage, conditions of work ensuring a decent standard of life... and promote cottage industries...",
    part: "Part IV: Directive Principles of State Policy",
    landmarkCases: [],
    tags: ["DPSP", "Labour Rights", "Welfare State", "Gandhian Principles"],
    limitationsAndExceptions: "A 'living wage' is an aspirational goal, not a legally enforceable right.",
    relatedArticles: ["Article 41", "Article 42"],
  },
  {
    id: "Article 43A",
    title: "Participation of workers in management of industries",
    summary: "The State shall take steps to secure the participation of workers in the management of industries.",
    detailedExplanation: "Added by the 42nd Amendment, this article directs the state to ensure workers are active participants in the decision-making processes of industries.",
    fullText: "The State shall take steps, by suitable legislation or in any other way, to secure the participation of workers in the management of undertakings, establishments or other organizations engaged in any industry.",
    part: "Part IV: Directive Principles of State Policy",
    landmarkCases: [],
    tags: ["DPSP", "Labour Rights", "Industrial Democracy"],
    limitationsAndExceptions: "This is a non-justiciable directive.",
    relatedArticles: ["Article 43"],
  },
  {
    id: "Article 43B",
    title: "Promotion of co-operative societies",
    summary: "The State shall endeavour to promote voluntary formation, autonomous functioning, democratic control and professional management of co-operative societies.",
    detailedExplanation: "Added by the 97th Amendment in 2011, this article aims to strengthen the co-operative movement by directing the state to promote co-operatives that are voluntary, autonomous, democratically controlled, and professionally managed.",
    fullText: "The State shall endeavour to promote voluntary formation, autonomous functioning, democratic control and professional management of co-operative societies.",
    part: "Part IV: Directive Principles of State Policy",
    landmarkCases: [],
    tags: ["DPSP", "Co-operative Societies", "Governance"],
    limitationsAndExceptions: "This is a non-justiciable directive.",
    relatedArticles: [],
  },
  {
    id: "Article 44",
    title: "Uniform civil code for the citizens",
    summary: "The State shall endeavour to secure for the citizens a uniform civil code throughout the territory of India.",
    detailedExplanation: "This article directs the state to strive for a Uniform Civil Code (UCC), which would replace diverse personal laws based on religion with a single set of secular civil laws governing matters like marriage, divorce, and inheritance. The goal is to promote national integration and gender justice. It remains a highly debated and unimplemented DPSP.",
    fullText: "The State shall endeavour to secure for the citizens a uniform civil code throughout the territory of India.",
    part: "Part IV: Directive Principles of State Policy",
    landmarkCases: [
      { caseName: "Mohd. Ahmed Khan v. Shah Bano Begum (1985)", caseSummary: "The Supreme Court's decision to grant maintenance to a divorced Muslim woman under secular law highlighted the need for a UCC." }
    ],
    tags: ["DPSP", "Uniform Civil Code", "Secularism", "Gender Justice"],
    limitationsAndExceptions: "This is a non-justiciable directive. Its implementation involves a perceived conflict with the fundamental right to freedom of religion.",
    relatedArticles: ["Article 14", "Article 25"],
  },
  {
    id: "Article 45",
    title: "Provision for early childhood care and education to children below the age of six years",
    summary: "The State shall endeavour to provide early childhood care and education for all children until they complete the age of six years.",
    detailedExplanation: "Originally for education up to 14 years, this article was amended by the 86th Amendment after Article 21A was added. It now directs the state to focus on early childhood care and education (ECCE) for children below six, forming the basis for programmes like Anganwadis.",
    fullText: "The State shall endeavour to provide early childhood care and education for all children until they complete the age of six years.",
    part: "Part IV: Directive Principles of State Policy",
    landmarkCases: [],
    tags: ["DPSP", "Education", "Welfare State", "Children"],
    limitationsAndExceptions: "This is a non-enforceable directive for early childhood care (age 0-6).",
    relatedArticles: ["Article 21A", "Article 51A"],
  },
  {
    id: "Article 46",
    title: "Promotion of educational and economic interests of Scheduled Castes, Scheduled Tribes and other weaker sections",
    summary: "The State shall promote with special care the educational and economic interests of the weaker sections, particularly SCs and STs, and protect them from social injustice and exploitation.",
    detailedExplanation: "This is a key directive for social justice, imposing a duty on the state to promote the educational and economic well-being of the most disadvantaged sections of society (SCs, STs, and other weaker sections) and protect them from exploitation. Reservation policies are rooted in this directive.",
    fullText: "The State shall promote with special care the educational and economic interests of the weaker sections of the people, and, in particular, of the Scheduled Castes and the Scheduled Tribes, and shall protect them from social injustice and all forms of exploitation.",
    part: "Part IV: Directive Principles of State Policy",
    landmarkCases: [],
    tags: ["DPSP", "Social Justice", "Reservation", "SC/ST"],
    limitationsAndExceptions: "This non-justiciable directive provides the constitutional justification for affirmative action policies.",
    relatedArticles: ["Article 15", "Article 16"],
  },
  {
    id: "Article 47",
    title: "Duty of the State to raise the level of nutrition and the standard of living and to improve public health",
    summary: "The State shall regard raising nutrition levels, the standard of living, and public health as its primary duties, and endeavour to prohibit intoxicating drinks and drugs.",
    detailedExplanation: "This directive sets public health and nutrition as primary duties of the state. It also directs the state to work towards the prohibition of alcohol and harmful drugs, except for medicinal purposes. Prohibition policies in some states are based on this directive.",
    fullText: "The State shall regard the raising of the level of nutrition and the standard of living of its people and the improvement of public health as among its primary duties and, in particular, the State shall endeavour to bring about prohibition of the consumption except for medicinal purposes of intoxicating drinks...",
    part: "Part IV: Directive Principles of State Policy",
    landmarkCases: [],
    tags: ["DPSP", "Public Health", "Welfare State", "Gandhian Principles"],
    limitationsAndExceptions: "The duty to improve public health is a primary but non-justiciable duty. The directive to prohibit intoxicating drinks is an 'endeavour' and not mandatory.",
    relatedArticles: ["Article 21"],
  },
  {
    id: "Article 48",
    title: "Organisation of agriculture and animal husbandry",
    summary: "The State shall endeavour to organise agriculture and animal husbandry on modern lines and prohibit the slaughter of cows, calves, and other milch and draught cattle.",
    detailedExplanation: "This directive has two parts: modernising agriculture and animal husbandry, and prohibiting the slaughter of cows and other useful cattle. This reflects both economic considerations and cultural sentiments, and is the basis for cattle protection laws in various states.",
    fullText: "The State shall endeavour to organise agriculture and animal husbandry on modern and scientific lines and shall, in particular, take steps for preserving and improving the breeds, and prohibiting the slaughter, of cows and calves and other milch and draught cattle.",
    part: "Part IV: Directive Principles of State Policy",
    landmarkCases: [],
    tags: ["DPSP", "Agriculture", "Gandhian Principles", "Animal Husbandry"],
    limitationsAndExceptions: "This is a non-justiciable directive.",
    relatedArticles: ["Article 48A"],
  },
   {
    id: "Article 48A",
    title: "Protection and improvement of environment and safeguarding of forests and wild life",
    summary: "The State shall endeavour to protect and improve the environment and to safeguard the forests and wildlife of the country.",
    detailedExplanation: "Added by the 42nd Amendment in 1976, this article places a directive duty on the State to protect the environment. It is the basis for key environmental laws like the Wildlife (Protection) Act, Forest (Conservation) Act, and Environment (Protection) Act.",
    fullText: "The State shall endeavour to protect and improve the environment and to safeguard the forests and wildlife of the country.",
    part: "Part IV: Directive Principles of State Policy",
    landmarkCases: [],
    tags: ["DPSP", "Environment", "Wildlife", "Forests"],
    limitationsAndExceptions: "This is a non-justiciable directive, complemented by the fundamental duty of citizens under Article 51A(g).",
    relatedArticles: ["Article 48", "Article 51A"],
  },
  {
    id: "Article 49",
    title: "Protection of monuments and places and objects of national importance",
    summary: "It is the obligation of the State to protect every monument, place, or object of artistic or historic interest declared to be of national importance.",
    detailedExplanation: "This directive imposes a duty on the state to protect India's cultural heritage from destruction, disfigurement, or export. The Archaeological Survey of India (ASI) is the primary instrument for fulfilling this directive.",
    fullText: "It shall be the obligation of the State to protect every monument or place or object of artistic or historic interest, declared by or under law made by Parliament to be of national importance, from spoliation, disfigurement, destruction, removal, disposal or export...",
    part: "Part IV: Directive Principles of State Policy",
    landmarkCases: [],
    tags: ["DPSP", "Culture", "Heritage", "Monuments"],
    limitationsAndExceptions: "This obligation applies specifically to monuments and objects that have been declared of 'national importance' by law.",
    relatedArticles: ["Article 51A"],
  },
  {
    id: "Article 50",
    title: "Separation of judiciary from executive",
    summary: "The State shall take steps to separate the judiciary from the executive in the public services of the State.",
    detailedExplanation: "This DPSP is crucial for ensuring the independence and impartiality of the judiciary. It directs the state to separate judicial functions from executive functions. This principle has been largely implemented in the criminal justice system through the Code of Criminal Procedure (CrPC), 1973.",
    fullText: "The State shall take steps to separate the judiciary from the executive in the public services of the State.",
    part: "Part IV: Directive Principles of State Policy",
    landmarkCases: [],
    tags: ["DPSP", "Judiciary", "Separation of Powers", "Governance"],
    limitationsAndExceptions: "While largely implemented, some overlap in administrative functions can still exist.",
    relatedArticles: [],
  },
  {
    id: "Article 51",
    title: "Promotion of international peace and security",
    summary: "The State shall endeavour to promote international peace, maintain just relations between nations, foster respect for international law, and encourage settlement of international disputes by arbitration.",
    detailedExplanation: "This article outlines India's foreign policy principles: (a) promote international peace, (b) maintain just relations, (c) foster respect for international law, and (d) encourage arbitration for disputes. These principles have guided India's policy of non-alignment and peaceful coexistence.",
    fullText: "The State shall endeavour to—\n(a) promote international peace and security;\n(b) maintain just and honourable relations between nations;\n(c) foster respect for international law and treaty obligations...\n(d) encourage settlement of international disputes by arbitration.",
    part: "Part IV: Directive Principles of State Policy",
    landmarkCases: [],
    tags: ["DPSP", "Foreign Policy", "International Law", "Peace"],
    limitationsAndExceptions: "These are non-justiciable guiding principles for foreign policy.",
    relatedArticles: [],
  },
  {
    id: "Article 51A",
    title: "Fundamental duties",
    summary: "Lists eleven fundamental duties of every citizen, added by the 42nd Amendment (1976) based on the Swaran Singh Committee recommendations.",
    detailedExplanation: "Added by the 42nd Amendment (1976) on the recommendation of the Sardar Swaran Singh Committee and inspired by the Soviet Constitution, this article lists the duties of citizens. They are non-justiciable. Originally 10, the 11th duty (education for children 6-14) was added by the 86th Amendment (2002). Key duties include abiding by the Constitution, respecting the National Flag and Anthem, and protecting the sovereignty, unity, and integrity of India.",
    fullText: "It shall be the duty of every citizen of India—\n(a) to abide by the Constitution and respect its ideals and institutions, the National Flag and the National Anthem;\n(b) to cherish and follow the noble ideals which inspired our national struggle for freedom;\n(c) to uphold and protect the sovereignty, unity and integrity of India;\n(d) to defend the country and render national service when called upon to do so;\n(e) to promote harmony and the spirit of common brotherhood...;\n(f) to value and preserve the rich heritage of our composite culture;\n(g) to protect and improve the natural environment...;\n(h) to develop the scientific temper, humanism and the spirit of inquiry and reform;\n(i) to safeguard public property and to abjure violence;\n(j) to strive towards excellence...;\n(k) who is a parent or guardian to provide opportunities for education to his child... between the age of six and fourteen years.",
    part: "Part IVA: Fundamental Duties",
    landmarkCases: [],
    tags: ["Fundamental Duties", "Citizenship", "Responsibility"],
    limitationsAndExceptions: "Fundamental Duties are non-justiciable and apply only to Indian citizens.",
    relatedArticles: ["Article 21A", "Article 45"],
    fillInTheBlanks: [{ question: "It shall be the ____ of every citizen of India to abide by the Constitution.", answer: "duty" }]
  }
];